// Copyright ThesmOS B.V. 2026
// SPDX-License-Identifier: MIT

package enumerate_test

import (
	"path/filepath"
	"strings"
	"testing"

	"go.dokimi.dev/assert"
	"go.dokimi.dev/assert/expect"

	"go.dokimi.dev/mutate/internal/enumerate"
	"go.dokimi.dev/mutate/internal/load"
	"go.dokimi.dev/mutate/internal/spec"
)

const steps = `package fixture

func steps(n int) int {
	if n > 0 {
		n--
	}
	if n > 0 {
		n--
	}
	return n
}
`

const clamp = `package fixture

func clamp(x, lo, hi int) int {
	if x < lo {
		return lo
	}
	if x > hi {
		return hi
	}
	return x
}
`

// generatedHeader is the first line of a file that a generator writes.
const generatedHeader = "// Code generated by hand. DO NOT EDIT.\n\n"

func TestEnumerate(t *testing.T) {
	t.Parallel()

	t.Run("Enumerate", func(t *testing.T) {
		t.Parallel()

		t.Run("keys identical sites by their occurrence", func(t *testing.T) {
			t.Parallel()
			r := all(t, map[string]string{"steps.go": steps})
			var falses []*enumerate.Mutant
			for _, m := range r.Mutants {
				if m.Kind == spec.RORFalse {
					falses = append(falses, m)
				}
			}
			assert.Length(t, falses, 2, "both comparisons have a ror-false mutant")
			for i, m := range falses {
				expect.Equal(t, m.Occurrence, i, "the occurrence counts the sites of one key's fields")
			}
			expect.NotEqual(t, falses[0].Key, falses[1].Key, "the two sites have two keys")
			// The digest was computed with printf and sha256sum, outside Go.
			expect.Equal(t, falses[1].Key, "681ab23c877298d7", "the second key is the digest of its fields")
		})

		t.Run("keeps every key when the code above a site moves", func(t *testing.T) {
			t.Parallel()
			before := all(t, map[string]string{"steps.go": steps})
			moved := strings.Replace(steps, "func steps", "func other() {}\n\n// steps counts down.\nfunc steps", 1)
			after := all(t, map[string]string{"steps.go": moved})
			assert.Length(t, after.Mutants, len(before.Mutants), "the move adds no mutant")
			for i, m := range before.Mutants {
				a := after.Mutants[i]
				expect.Equal(t, a.Key, m.Key, "a site keeps its key")
				expect.Equal(t, a.Site.StartPos.Line, m.Site.StartPos.Line+3, "and moves three lines down")
			}
		})

		t.Run("reads only the files that the build compiles and that no generator writes", func(t *testing.T) {
			t.Parallel()
			r := all(t, map[string]string{
				"a.go":       "package fixture\n\nfunc used(x int) int { return x + 1 }\n",
				"gen.go":     generatedHeader + "package fixture\n\nfunc generated(x int) int { return x * 2 }\n",
				"ignored.go": "//go:build ignore\n\npackage other\n\nfunc ignored(x int) int { return x - 3 }\n",
				"a_test.go":  "package fixture\n\nfunc helper(x int) int { return x / 4 }\n",
			})
			assert.Equal(t, listing(r, ""), `used sbr-zero 0: return x + 1 -> "return 0"
used aor 0: x + 1 -> "x - 1"
`, "the mutants are in the build's own source alone")
		})

		t.Run(
			"reads a generated file that contains the include directive before its package clause",
			func(t *testing.T) {
				t.Parallel()
				r := all(t, map[string]string{
					"included.go": "// Code generated by codecgen. DO NOT EDIT.\n//dokimi:mutate-include\n\npackage fixture\n\n" +
						"func included(x int) int { return x * 2 }\n",
					"late.go": "// Code generated by codecgen. DO NOT EDIT.\n\npackage fixture\n\n//dokimi:mutate-include\n" +
						"func late(x int) int { return x * 3 }\n",
				})
				assert.Equal(t, listing(r, string(spec.AOR)), "included aor 0: x * 2 -> \"x / 2\"\n",
					"only the file with the directive before its package clause is a target")
			},
		)

		t.Run("lists each generated file that it leaves out with the mutants at its sites", func(t *testing.T) {
			t.Parallel()
			// Each function has two mutants: a return of zero values and an
			// aor. The annotation of b_gen.go suppresses nothing and is no
			// problem, because the file is no target.
			r := all(t, map[string]string{
				"a.go": "package fixture\n\nfunc used(x int) int { return x + 1 }\n",
				"a_gen.go": generatedHeader + "package fixture\n\n" +
					"func doubled(x int) int { return x * 2 }\n\nfunc tripled(x int) int { return x * 3 }\n",
				"b_gen.go": generatedHeader + "package fixture\n\n" +
					"//dokimi:mutate-skip aor: a generated file is no target\nconst k = 2\n",
			})
			expect.Equal(t, r.Generated, []enumerate.Generated{{File: "a_gen.go", Mutants: 4}, {File: "b_gen.go"}},
				"the generated files are listed in file order with their mutants")
			expect.Empty(t, r.Problems, "and the annotation of a file that the run leaves out is no problem")
		})

		t.Run("reads every generated file as a target under IncludeGenerated", func(t *testing.T) {
			t.Parallel()
			r := enumerateFixture(t, map[string]string{
				"a.go": "package fixture\n\nfunc used(x int) int { return x + 1 }\n",
				"gen.go": generatedHeader + "package fixture\n\n" +
					"//dokimi:mutate-skip aor: no arithmetic below\nfunc generated(x int) int { return x }\n",
			}, enumerate.Options{IncludeGenerated: true})
			expect.Equal(t, listing(r, ""), `used sbr-zero 0: return x + 1 -> "return 0"
used aor 0: x + 1 -> "x - 1"
generated sbr-zero 0: return x -> "return 0"
`, "the generated file's mutants are the target's own")
			expect.Equal(t, r.Generated, []enumerate.Generated{{File: "gen.go", Mutants: 1, Included: true}},
				"the generated file is listed as included")
			expect.Equal(t, problems(r), "stale-annotation gen.go:5: the annotation suppresses no mutant\n",
				"and its annotations apply as those of any target")
		})

		t.Run("names each file relative to the module root", func(t *testing.T) {
			t.Parallel()
			dir := moduleDir(t, map[string]string{"sub/a.go": "package sub\n\nfunc F(x int) int { return x + 1 }\n"})
			sub := loadDir(t, filepath.Join(dir, "sub"))
			r := enumerate.Enumerate(sub, spec.Load(), enumerate.Options{
				Lines: []enumerate.Range{{File: "sub/a.go", First: 3, Last: 3}},
			})
			assert.NotEmpty(t, r.Mutants, "the function has mutants")
			for _, m := range r.Mutants {
				expect.Equal(t, m.Site.File.Name, "sub/a.go", "each mutant names its file from the module root")
				expect.Equal(t, m.Status, enumerate.Runnable, "and the selection of that file selects it")
			}
			m := r.Mutants[0]
			want := enumerate.Key(
				spec.Load().Catalogue.Key,
				"sub/a.go",
				"F",
				m.Kind,
				enumerate.Tokens([]byte("return x + 1")),
				0,
			)
			expect.Equal(t, m.Key, want, "the key hashes the file's name from the module root")
		})

		t.Run("marks the mutants outside the selection", func(t *testing.T) {
			t.Parallel()
			r := enumerateFixture(t, map[string]string{"clamp.go": clamp},
				enumerate.Options{Lines: []enumerate.Range{{File: "clamp.go", First: 7, Last: 9}}})
			assert.Equal(t, statuses(r), `clamp sbr-delete 0: not-selected
clamp ror-boundary 0: not-selected
clamp ror-false 0: not-selected
clamp sbr-zero 0: not-selected
clamp sbr-zero 2: not-selected
`, "every mutant outside the lines is not-selected")
		})

		t.Run("marks every mutant not selected under a selection without a range", func(t *testing.T) {
			t.Parallel()
			r := enumerateFixture(
				t,
				map[string]string{"clamp.go": clamp},
				enumerate.Options{Lines: []enumerate.Range{}},
			)
			assert.NotEmpty(t, r.Mutants, "the fixture has mutants")
			for _, m := range r.Mutants {
				expect.Equal(t, m.Status, enumerate.NotSelected, "an empty selection selects no mutant")
			}
		})

		t.Run("ranks not selected before suppressed and suppressed before not viable", func(t *testing.T) {
			t.Parallel()
			// The aor mutant of x * weight divides an integer by a constant 0,
			// which the compiler rejects.
			r := enumerateFixture(t, map[string]string{"weight.go": `package fixture

import "log"

const weight = 0

func outside(x int) int {
	y := x * weight //dokimi:mutate-skip aor: a test of the ranking
	return y + 1
}

func ruled(n int) {
	log.Println(n * weight)
}

func inside(x int) int {
	y := x * weight //dokimi:mutate-skip aor: suppressed before not viable
	return y + 1
}

func plain(x int) int {
	y := x * weight
	return y + 1
}
`}, enumerate.Options{Lines: []enumerate.Range{{File: "weight.go", First: 16, Last: 24}}})
			expect.Equal(t, statuses(r), `outside aor 0: not-selected
outside sbr-zero 0: not-selected
outside aor 1: not-selected
ruled sbr-delete 0: not-selected
ruled aor 0: not-selected
inside aor 0: suppressed
plain aor 0: not-viable
`, "the first status that applies is the mutant's")
			for _, m := range r.Mutants {
				if m.Status == enumerate.NotSelected {
					expect.Equal(
						t,
						string(m.Rule)+m.Reason,
						"",
						"a mutant outside the selection states no rule and no reason",
					)
				}
			}
			expect.Empty(t, r.Problems, "an annotation outside the selection still applies")
		})

		t.Run("lists every site of a file that imports C as skipped", func(t *testing.T) {
			t.Parallel()
			src := "package fixture\n\n// int twice(int x) { return 2 * x; }\nimport \"C\"\n\nfunc Twice(x int) int {\n" +
				"\tif x > 3 && x < 10 { //dokimi:mutate-skip ror: no mutant here\n\t\tx += int(C.twice(C.int(x)))\n\t}\n" +
				"\treturn x - 1\n}\n"
			r := all(
				t,
				map[string]string{"c.go": src, "g.go": "package fixture\n\nfunc Plain(x int) bool { return x > 2 }\n"},
			)
			expect.Equal(t, skipped(r, src), `if x > 3 && x < 10 { //dokimi:mutate-skip ror: no mutant here
		x += int(C.twice(C.int(x)))
	}: file imports C
x > 3 && x < 10: file imports C
x > 3: file imports C
x < 10: file imports C
x += int(C.twice(C.int(x))): file imports C
return x - 1: file imports C
x - 1: file imports C
`, "each site of the cgo file is skipped at its position in the file that imports C")
			for _, s := range r.Skipped {
				expect.Equal(t, s.File, "c.go", "every skipped site is in c.go")
			}
			for _, m := range r.Mutants {
				expect.Equal(t, m.Site.File.Name, "g.go", "every mutant is in g.go")
			}
			expect.Equal(t, problems(r), "stale-annotation c.go:7: the annotation suppresses no mutant\n",
				"and the annotation of a skipped site suppresses nothing")
		})

		t.Run("returns the same result for one package on every call", func(t *testing.T) {
			t.Parallel()
			p := fixture(t, map[string]string{"clamp.go": clamp, "steps.go": steps})
			d := spec.Load()
			assert.Deterministic(t, func(p *load.Package) (string, error) {
				r := enumerate.Enumerate(p, d, enumerate.Options{})
				var keys strings.Builder
				for _, m := range r.Mutants {
					keys.WriteString(m.Key + "\n")
				}
				return listing(r, "") + statuses(r) + keys.String(), nil
			}, p, "Enumerate orders every list that it builds from maps")
		})
	})
}
