// Copyright ThesmOS B.V. 2026
// SPDX-License-Identifier: MIT

package enumerate_test

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"go.dokimi.dev/mutate/internal/enumerate"
	"go.dokimi.dev/mutate/internal/spec"
)

const steps = `package fixture

func steps(n int) int {
	if n > 0 {
		n--
	}
	if n > 0 {
		n--
	}
	return n
}
`

const clamp = `package fixture

func clamp(x, lo, hi int) int {
	if x < lo {
		return lo
	}
	if x > hi {
		return hi
	}
	return x
}
`

func TestEnumerate(t *testing.T) {
	t.Parallel()
	t.Run("the definition's values", func(t *testing.T) {
		t.Parallel()
		d := spec.Load()
		t.Run("are the catalogue's kinds in its order", func(t *testing.T) {
			t.Parallel()
			var catalogue []string
			for _, k := range d.Catalogue.Kinds {
				catalogue = append(catalogue, k.ID)
			}
			ours := []string{
				enumerate.AOR, enumerate.RORBoundary, enumerate.RORTrue, enumerate.RORFalse,
				enumerate.LCRLeft, enumerate.LCRRight, enumerate.LCRTrue, enumerate.LCRFalse,
				enumerate.UOIIncDec, enumerate.UOINot, enumerate.UOIMinus, enumerate.SBRDelete, enumerate.SBRZero,
			}
			if strings.Join(ours, " ") != strings.Join(catalogue, " ") {
				t.Errorf("kinds %v, and the catalogue defines %v", ours, catalogue)
			}
		})
		t.Run("are the overlay's skip reasons in its order", func(t *testing.T) {
			t.Parallel()
			var overlay []string
			for _, s := range d.Overlay.Skips {
				overlay = append(overlay, s.Reason)
			}
			ours := []string{
				enumerate.SkipConstant,
				enumerate.SkipTypeParameter,
				enumerate.SkipContextShift,
				enumerate.SkipNamedBool,
				enumerate.SkipSideEffects,
				enumerate.SkipCgo,
			}
			if strings.Join(ours, "|") != strings.Join(overlay, "|") {
				t.Errorf("skip reasons %v, and the overlay defines %v", ours, overlay)
			}
		})
		t.Run("are run errors of the protocol", func(t *testing.T) {
			t.Parallel()
			defined := map[string]bool{}
			for _, e := range d.Protocol.Errors {
				defined[e] = true
			}
			for _, code := range []string{enumerate.ErrorWithoutReason, enumerate.ErrorStale} {
				if !defined[code] {
					t.Errorf("%s is not a run error of the protocol", code)
				}
			}
		})
	})
	t.Run("Enumerate", func(t *testing.T) {
		t.Parallel()
		t.Run("keys identical sites by their occurrence", func(t *testing.T) {
			t.Parallel()
			r := enumerateFixture(t, map[string]string{"steps.go": steps})
			var falses []*enumerate.Mutant
			for _, m := range r.Mutants {
				if m.Kind == enumerate.RORFalse {
					falses = append(falses, m)
				}
			}
			if len(falses) != 2 {
				t.Fatalf("got %d ror-false mutants, want 2", len(falses))
			}
			for i, m := range falses {
				if m.Occurrence != i {
					t.Errorf("mutant %d has occurrence %d, want %d", i, m.Occurrence, i)
				}
			}
			// The digest was computed with printf and sha256sum, outside Go.
			if falses[0].Key == falses[1].Key || falses[1].Key != "681ab23c877298d7" {
				t.Errorf(
					"keys %s and %s, want two keys and the second 681ab23c877298d7",
					falses[0].Key,
					falses[1].Key,
				)
			}
		})
		t.Run("keeps every key when the code above a site moves", func(t *testing.T) {
			t.Parallel()
			before := enumerateFixture(t, map[string]string{"steps.go": steps})
			moved := strings.Replace(steps, "func steps", "func other() {}\n\n// steps counts down.\nfunc steps", 1)
			after := enumerateFixture(t, map[string]string{"steps.go": moved})
			if len(before.Mutants) != len(after.Mutants) {
				t.Fatalf("%d mutants before and %d after", len(before.Mutants), len(after.Mutants))
			}
			for i, m := range before.Mutants {
				a := after.Mutants[i]
				if m.Key != a.Key || a.Site.StartPos.Line != m.Site.StartPos.Line+3 {
					t.Errorf("%s at line %d has key %s, and at line %d key %s: want the same key three lines lower",
						m.Kind, m.Site.StartPos.Line, m.Key, a.Site.StartPos.Line, a.Key)
				}
			}
		})
		t.Run("reads only the files that the build compiles and that no generator writes", func(t *testing.T) {
			t.Parallel()
			r := enumerateFixture(t, map[string]string{
				"a.go":       "package fixture\n\nfunc used(x int) int { return x + 1 }\n",
				"gen.go":     "// Code generated by hand. DO NOT EDIT.\n\npackage fixture\n\nfunc generated(x int) int { return x * 2 }\n",
				"ignored.go": "//go:build ignore\n\npackage other\n\nfunc ignored(x int) int { return x - 3 }\n",
				"a_test.go":  "package fixture\n\nfunc helper(x int) int { return x / 4 }\n",
			})
			want(t, listing(r, ""), `used sbr-zero 0: return x + 1 -> "return 0"
used aor 0: x + 1 -> "x - 1"
`)
		})
		t.Run(
			"reads a generated file that contains the include directive before its package clause",
			func(t *testing.T) {
				t.Parallel()
				r := enumerateFixture(t, map[string]string{
					"included.go": "// Code generated by codecgen. DO NOT EDIT.\n//dokimi:mutate-include\n\npackage fixture\n\n" +
						"func included(x int) int { return x * 2 }\n",
					"late.go": "// Code generated by codecgen. DO NOT EDIT.\n\npackage fixture\n\n//dokimi:mutate-include\n" +
						"func late(x int) int { return x * 3 }\n",
				})
				want(t, listing(r, "aor"), `included aor 0: x * 2 -> "x / 2"
`)
			},
		)
		t.Run("lists each generated file that it leaves out with the mutants at its sites", func(t *testing.T) {
			t.Parallel()
			// Each function has two mutants: a return of zero values and an
			// aor. The annotation of b_gen.go suppresses nothing and is no
			// problem, because the file is no target.
			r := enumerateFixture(t, map[string]string{
				"a.go": "package fixture\n\nfunc used(x int) int { return x + 1 }\n",
				"a_gen.go": "// Code generated by hand. DO NOT EDIT.\n\npackage fixture\n\n" +
					"func doubled(x int) int { return x * 2 }\n\nfunc tripled(x int) int { return x * 3 }\n",
				"b_gen.go": "// Code generated by hand. DO NOT EDIT.\n\npackage fixture\n\n" +
					"//dokimi:mutate-skip aor: a generated file is no target\nconst k = 2\n",
			})
			if got := fmt.Sprint(r.Generated); got != "[{a_gen.go 4} {b_gen.go 0}]" || len(r.Problems) != 0 {
				t.Errorf(
					"generated %s and problems %v, want a_gen.go with 4 mutants, b_gen.go with none",
					got,
					r.Problems,
				)
			}
		})
		t.Run("names each file relative to the module root", func(t *testing.T) {
			t.Parallel()
			dir := t.TempDir()
			for name, text := range map[string]string{"go.mod": "module fixture\n\ngo 1.21\n", "sub/a.go": "package sub\n\nfunc F(x int) int { return x + 1 }\n"} {
				if err := os.MkdirAll(filepath.Dir(filepath.Join(dir, name)), 0o755); err != nil {
					t.Fatal(err)
				}
				if err := os.WriteFile(filepath.Join(dir, name), []byte(text), 0o644); err != nil {
					t.Fatal(err)
				}
			}
			p := loadDir(t, filepath.Join(dir, "sub"))
			r := enumerate.Enumerate(p, spec.Load(), []enumerate.Range{{File: "sub/a.go", First: 3, Last: 3}})
			for _, m := range r.Mutants {
				if m.Site.File.Name != "sub/a.go" || m.Status != enumerate.Runnable {
					t.Errorf(
						"%s is in %s with status %d, want sub/a.go and selected",
						m.Kind,
						m.Site.File.Name,
						m.Status,
					)
				}
			}
			if m := r.Mutants[0]; m.Key != enumerate.Key(
				"dokimi-mutate-key/1",
				"sub/a.go",
				"F",
				m.Kind,
				enumerate.Tokens([]byte("return x + 1")),
				0,
			) {
				t.Errorf("the key of %s does not hash the file sub/a.go", m.Kind)
			}
		})
		t.Run("marks the mutants outside the selection", func(t *testing.T) {
			t.Parallel()
			r := enumerateFixture(
				t,
				map[string]string{"clamp.go": clamp},
				enumerate.Range{File: "clamp.go", First: 7, Last: 9},
			)
			want(t, statuses(r), `clamp sbr-delete 0: not-selected
clamp ror-boundary 0: not-selected
clamp ror-false 0: not-selected
clamp sbr-zero 0: not-selected
clamp sbr-zero 2: not-selected
`)
		})
		t.Run("marks every mutant not selected under a selection without a range", func(t *testing.T) {
			t.Parallel()
			r := enumerate.Enumerate(fixture(t, map[string]string{"clamp.go": clamp}), spec.Load(), []enumerate.Range{})
			for _, m := range r.Mutants {
				if m.Status != enumerate.NotSelected {
					t.Errorf("%s %s has status %d, want not selected", m.Site.Scope, m.Kind, m.Status)
				}
			}
			if len(r.Mutants) == 0 {
				t.Error("the fixture has no mutant")
			}
		})
		t.Run("ranks not selected before suppressed and suppressed before not viable", func(t *testing.T) {
			t.Parallel()
			// The aor mutant of x * weight divides an integer by a constant 0,
			// which the compiler rejects.
			r := enumerateFixture(t, map[string]string{"weight.go": `package fixture

import "log"

const weight = 0

func outside(x int) int {
	y := x * weight //dokimi:mutate-skip aor: a test of the ranking
	return y + 1
}

func ruled(n int) {
	log.Println(n * weight)
}

func inside(x int) int {
	y := x * weight //dokimi:mutate-skip aor: suppressed before not viable
	return y + 1
}

func plain(x int) int {
	y := x * weight
	return y + 1
}
`}, enumerate.Range{File: "weight.go", First: 16, Last: 24})
			want(t, statuses(r), `outside aor 0: not-selected
outside sbr-zero 0: not-selected
outside aor 1: not-selected
ruled sbr-delete 0: not-selected
ruled aor 0: not-selected
inside aor 0: suppressed
plain aor 0: not-viable
`)
			for _, m := range r.Mutants {
				if m.Status == enumerate.NotSelected && (m.Rule != "" || m.Reason != "") {
					t.Errorf(
						"%s %s is not selected and states the rule %q and the reason %q",
						m.Site.Scope,
						m.Kind,
						m.Rule,
						m.Reason,
					)
				}
			}
			if len(r.Problems) != 0 {
				t.Errorf("problems %v, want none: annotations outside the selection still apply", r.Problems)
			}
		})
		t.Run("lists every site of a file that imports C as skipped", func(t *testing.T) {
			t.Parallel()
			src := "package fixture\n\n// int twice(int x) { return 2 * x; }\nimport \"C\"\n\nfunc Twice(x int) int {\n\tif x > 3 && x < 10 { //dokimi:mutate-skip ror: no mutant here\n\t\tx += int(C.twice(C.int(x)))\n\t}\n\treturn x - 1\n}\n"
			r := enumerateFixture(
				t,
				map[string]string{"c.go": src, "g.go": "package fixture\n\nfunc Plain(x int) bool { return x > 2 }\n"},
			)
			var b strings.Builder
			for _, s := range r.Skipped {
				fmt.Fprintf(
					&b,
					"%s %d:%d-%d:%d %s: %s\n",
					s.File,
					s.Start.Line,
					s.Start.Column,
					s.End.Line,
					s.End.Column,
					src[offset(src, s.Start):offset(src, s.End)],
					s.Reason,
				)
			}
			want(t, b.String(), `c.go 7:2-9:3 if x > 3 && x < 10 { //dokimi:mutate-skip ror: no mutant here
		x += int(C.twice(C.int(x)))
	}: file imports C
c.go 7:5-7:20 x > 3 && x < 10: file imports C
c.go 7:5-7:10 x > 3: file imports C
c.go 7:14-7:20 x < 10: file imports C
c.go 8:3-8:30 x += int(C.twice(C.int(x))): file imports C
c.go 10:2-10:14 return x - 1: file imports C
c.go 10:9-10:14 x - 1: file imports C
`)
			for _, m := range r.Mutants {
				if m.Site.File.Name != "g.go" {
					t.Errorf("%s mutates %s, want only g.go", m.Kind, m.Site.File.Name)
				}
			}
			want(t, problems(r), "stale-annotation c.go:7: the annotation suppresses no mutant\n")
		})
	})
}
