// Copyright ThesmOS B.V. 2026
// SPDX-License-Identifier: MIT

package run_test

import (
	"context"
	"fmt"
	"io/fs"
	"maps"
	"os"
	"path/filepath"
	"runtime"
	"slices"
	"strings"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	"go.dokimi.dev/assert"

	"go.dokimi.dev/mutate/internal/record"
	"go.dokimi.dev/mutate/internal/run"
	"go.dokimi.dev/mutate/internal/selection"
	"go.dokimi.dev/mutate/internal/spec"
)

// The name of scale's own test file and of its other package's source.
const (
	scaleTestFile = "scale_test.go"
	otherFile     = "other/other.go"
)

// genFile is the generated file of generated.
const genFile = "gen.go"

// generated is a package whose only function is in a generated file, and
// whose test checks that function.
var generated = map[string]string{
	genFile: "// Code generated by hand. DO NOT EDIT.\n\npackage fixture\n\nfunc Double(x int) int { return x * 2 }\n",
	"gen_test.go": `package fixture

import "testing"

func TestDouble(t *testing.T) {
	if Double(2) != 4 {
		t.Error("Double(2) != 4")
	}
}
`,
}

// arithNotSelected are the verdicts of arith's mutants under a selection
// that contains none of them.
const arithNotSelected = `Add sbr-zero 0: not-selected
Add aor 0: not-selected
Sub sbr-zero 0: not-selected
Sub aor 0: not-selected
Unused sbr-zero 0: not-selected
Unused aor 0: not-selected
`

func TestRun(t *testing.T) {
	t.Parallel()

	t.Run("Run", func(t *testing.T) {
		t.Parallel()

		t.Run("gives each mutant the verdict of its run and states the run", func(t *testing.T) {
			t.Parallel()
			dir := module(t, arithFiles)
			rec := runIn(t, dir, run.Config{})
			assert.Equal(t, verdicts(rec), arithVerdicts, "each mutant has the verdict of its run")
			assert.Equal(t, rec.Record, protocol.Record.Name, "the record names the protocol's record")
			assert.Equal(t, rec.Version, protocol.Record.Version, "and its version")
			assert.Equal(t, rec.Catalogue, definition.Version, "the record states the catalogue's version")
			assert.Equal(t, rec.Overlay, definition.Overlay.Version, "and the overlay's version")
			assert.Equal(t, rec.Engine.Name, run.Engine, "the record names the engine")
			assert.Equal(t, rec.Target, record.Target{Language: definition.Overlay.Language, Name: "fixture"},
				"the target is the package's import path")
			assert.Equal(t, rec.Skipped, []record.Skip{{
				File:   arithFile,
				Start:  record.Position{Line: 3, Column: 15},
				End:    record.Position{Line: 3, Column: 20},
				Reason: "constant expression",
			}}, "the record lists the constant expression that has no mutant")
			assert.Equal(t, rec.Score, new(2.0/6.0), "the tests detect two of the six mutants")
			assert.Equal(t, rec.Control.Opening.Sites, 6, "the opening control run counts the six sites")
			assert.Equal(t, rec.Control.Opening.SitesExecuted, 4, "and the four that the tests execute")
			assert.NotNil(t, rec.Control.Closing, "the closing control run runs")
			for _, m := range rec.Mutants {
				ran := m.Verdict == spec.Killed || m.Verdict == spec.Survived
				assert.Equal(t, m.Seconds != nil, ran, "a mutant states its time when it ran")
			}
			root, err := filepath.EvalSymlinks(dir)
			assert.NoError(t, err, "the module's directory resolves")
			assert.Equal(t, rec.Root, root, "the root is the module's directory with its links resolved")
			assert.Equal(t, rec.Toolchain, runtime.Version(), "the record states the toolchain that built the engine")
			assert.Matches(t, rec.Inputs, `^sha256:[0-9a-f]{64}$`, "the inputs digest is a SHA-256 digest")
			started, err := time.Parse(time.RFC3339, rec.StartedAt)
			assert.NoError(t, err, "the start is an RFC 3339 time")
			finished, err := time.Parse(time.RFC3339, rec.FinishedAt)
			assert.NoError(t, err, "the end is an RFC 3339 time")
			assert.Pairwise(t, []time.Time{started, finished}, func(earlier, later time.Time) bool {
				return !later.Before(earlier)
			}, "the run ends after it starts")
		})

		t.Run("passes each mutant to Verdict with the number of mutants and its file's path", func(t *testing.T) {
			t.Parallel()
			dir := module(t, with(arithFiles, map[string]string{
				arithFile: strings.Replace(arith, "func Add", fmt.Sprintf("%s %s: Sub checks it\nfunc Add",
					annotation, spec.AOR), 1),
			}))
			var mu sync.Mutex
			var mutants []record.Mutant
			var counts []int
			var paths []string
			rec := runIn(t, dir, run.Config{Verdict: func(m record.Mutant, n int, path string) {
				mu.Lock()
				defer mu.Unlock()
				mutants, counts, paths = append(mutants, m), append(counts, n), append(paths, path)
			}})
			assert.Permutation(t, mutants, rec.Mutants, "Verdict receives each mutant once, as the record states it")
			assert.Equal(t, mutants[0].Verdict, spec.Suppressed, "the first verdict is the one that no run decides")
			assert.Equal(t, slices.Compact(counts), []int{len(rec.Mutants)},
				"each call states the number of the run's mutants")
			wd, err := os.Getwd()
			if err == nil {
				wd, err = filepath.EvalSymlinks(wd)
			}
			assert.NoError(t, err, "the working directory resolves")
			var got, want []string
			for i, m := range mutants {
				got = append(got, filepath.Join(wd, paths[i]))
				want = append(want, filepath.Join(rec.Root, filepath.FromSlash(m.File)))
			}
			assert.Equal(t, got, want, "each path leads from the working directory to the mutant's file")
		})

		t.Run("marks the mutants outside the selection", func(t *testing.T) {
			t.Parallel()
			dir := module(t, arithFiles)
			var reported atomic.Int64
			rec := runIn(t, dir, run.Config{
				Lines:   []selection.Lines{{Path: filepath.Join(dir, arithFile), First: 7, Last: 7}},
				Verdict: func(record.Mutant, int, string) { reported.Add(1) },
			})
			assert.Equal(t, verdicts(rec), `Add sbr-zero 0: not-selected
Add aor 0: not-selected
Sub sbr-zero 0: survived
Sub aor 0: survived
Unused sbr-zero 0: not-selected
Unused aor 0: not-selected
`, "the mutants of Sub alone run")
			assert.Equal(t, reported.Load(), int64(len(rec.Mutants)), "Verdict receives every mutant")
		})

		t.Run("states the ranges of the selection in the package's files", func(t *testing.T) {
			t.Parallel()
			dir := module(t, arithFiles)
			rec := runIn(t, dir, run.Config{Lines: []selection.Lines{
				{Path: filepath.Join(dir, arithFile), First: 7, Last: 7},
				{Path: filepath.Join(dir, filepath.FromSlash(otherFile)), First: 1, Last: 9},
			}})
			assert.Equal(t, rec.Selection, []record.Range{{File: arithFile, First: 7, Last: 7}},
				"the selection states the range of the package's file alone")
		})

		t.Run("selects no mutant under a selection without a range", func(t *testing.T) {
			t.Parallel()
			rec := runIn(t, module(t, arithFiles), run.Config{Lines: []selection.Lines{}})
			assert.Equal(t, verdicts(rec), arithNotSelected, "every mutant is outside the selection")
			assert.That(t, rec.Selection).
				NotNil("the record states the selection").
				Empty("and the selection contains no range")
			assert.Nil(t, rec.Control, "a run without a mutant to run runs no control run")
		})

		t.Run("runs no test when no mutant is left to run", func(t *testing.T) {
			t.Parallel()
			// TestBroken fails with no mutant active, and the selection
			// contains no mutant.
			dir := module(t, with(arithFiles, map[string]string{
				arithTestFile: arithTest + "\nfunc TestBroken(t *testing.T) {\n\tt.Fatal(\"broken\")\n}\n",
			}))
			lines := []selection.Lines{{Path: filepath.Join(dir, arithFile), First: 1, Last: 1}}
			rec := runIn(t, dir, run.Config{Lines: lines})
			assert.Equal(t, verdicts(rec), arithNotSelected, "every mutant is outside the selection")
			assert.Nil(t, rec.Control, "the run runs no control run")
			assert.False(t, rec.Failed(), "the failing test does not fail the run")
		})

		t.Run("lists every mutant without a run under List", func(t *testing.T) {
			t.Parallel()
			rec := runIn(t, module(t, arithFiles), run.Config{List: true})
			assert.Equal(t, verdicts(rec), "Add sbr-zero 0: \nAdd aor 0: \nSub sbr-zero 0: \nSub aor 0: \n"+
				"Unused sbr-zero 0: \nUnused aor 0: \n", "a listing leaves each mutant to test without a verdict")
			assert.Nil(t, rec.Control, "a listing runs no control run")
			assert.Empty(t, rec.Errors, "the instrumented package type-checks")
		})

		t.Run(
			"states the build error of an instrumentation that the type checker rejects under List",
			func(t *testing.T) {
				t.Parallel()
				dir := module(t, with(arithFiles, map[string]string{"hiding.go": hiding}))
				rec := runIn(t, dir, run.Config{List: true})
				assert.Equal(t, codes(rec), []spec.ErrorCode{spec.ErrorBuild}, "the instrumentation fails")
				assert.HasPrefix(
					t,
					rec.Errors[0].Message,
					"render: the type checker rejects the instrumented package: ",
					"the message states the type checker's verdict",
				)
			},
		)

		t.Run("lists the generated files that the run leaves out", func(t *testing.T) {
			t.Parallel()
			rec := runIn(t, module(t, generated), run.Config{})
			assert.Equal(t, rec.Generated, []record.Generated{{File: genFile, Mutants: 2}},
				"the record lists the generated file and its mutants")
			assert.Empty(t, rec.Mutants, "the run leaves out the mutants of the generated file")
		})

		t.Run("tests the mutants of the generated files under IncludeGenerated", func(t *testing.T) {
			t.Parallel()
			rec := runIn(t, module(t, generated), run.Config{IncludeGenerated: true})
			assert.Equal(t, rec.Generated, []record.Generated{{File: genFile, Mutants: 2, Included: true}},
				"the record lists the generated file as included")
			assert.Equal(t, verdicts(rec), `Double sbr-zero 0: killed [TestDouble]
Double aor 0: killed [TestDouble]
`, "the mutants of the generated file run")
		})

		t.Run("gives no-coverage to every mutant of a package without a test file", func(t *testing.T) {
			t.Parallel()
			rec := runIn(t, module(t, map[string]string{arithFile: arith}), run.Config{})
			assert.Equal(t, verdicts(rec), `Add sbr-zero 0: no-coverage
Add aor 0: no-coverage
Sub sbr-zero 0: no-coverage
Sub aor 0: no-coverage
Unused sbr-zero 0: no-coverage
Unused aor 0: no-coverage
`, "no test covers a mutant")
			assert.Nil(t, rec.Control, "a package without a test binary runs no control run")
			assert.Equal(t, rec.Score, new(0.0), "the tests detect none of the mutants")
		})

		t.Run("counts the tests of the other packages of the suite that link the package", func(t *testing.T) {
			t.Parallel()
			dir := module(t, scale)
			own := runIn(t, dir, run.Config{})
			assert.Equal(t, verdicts(own), "Scale sbr-zero 0: killed [TestScaleByOne]\nScale aor 0: survived\n",
				"the package's own test cannot tell a multiplication from a division")
			rec := runIn(t, dir, run.Config{Suite: []string{"./..."}})
			assert.Equal(t, verdicts(rec), `Scale sbr-zero 0: killed [TestScaleByOne]
Scale aor 0: killed [fixture/conformance: TestScale]
`, "the test of the package conformance detects the division")
			assert.Empty(t, rec.Errors, "the run states no run error")
			assert.Equal(t, rec.Suite, []string{conformance},
				"the suite names the package whose tests link the package")
			assert.Nil(t, own.Suite, "a run without a suite states none")
			assert.NotEqual(t, rec.Inputs, own.Inputs, "the inputs digest covers the suite")
			assert.Equal(t, rec.Control.Opening.SitesExecuted, 2, "the control run executes both sites")
			assert.NotNil(t, rec.Control.Closing, "the closing control run runs")
		})

		t.Run("runs the suite's other test binaries when the package has no test file", func(t *testing.T) {
			t.Parallel()
			files := maps.Clone(scale)
			delete(files, scaleTestFile)
			rec := runIn(t, module(t, files), run.Config{Suite: []string{conformancePattern}})
			assert.Equal(t, verdicts(rec), `Scale sbr-zero 0: killed [fixture/conformance: TestScale]
Scale aor 0: killed [fixture/conformance: TestScale]
`, "the test of the package conformance detects both mutants")
			assert.Empty(t, rec.Errors, "the run states no run error")
		})

		t.Run("asks Admit for the workers times the largest memory ceiling before the runs", func(t *testing.T) {
			t.Parallel()
			var asked int64
			released := false
			admit := func(_ context.Context, bytes int64) (func(), bool) {
				asked = bytes
				return func() { released = true }, true
			}
			rec := runIn(t, module(t, arithFiles), run.Config{Workers: 2, Admit: admit})
			assert.Equal(t, verdicts(rec), arithVerdicts, "the admitted run gives each mutant its verdict")
			var ceiling int64
			if c := rec.Limits[0].MemoryCeilingBytes; c != nil {
				ceiling = *c
			}
			assert.Equal(t, asked, 2*ceiling, "Admit receives the memory of the two workers' runs")
			assert.True(t, released, "the run releases what Admit admitted")
		})

		t.Run("stops the runs when the caller's context ends before Admit admits them", func(t *testing.T) {
			t.Parallel()
			rec := runIn(t, module(t, arithFiles), run.Config{
				Admit: func(context.Context, int64) (func(), bool) { return nil, false },
			})
			assert.Equal(t, verdicts(rec), `Add sbr-zero 0: not-run
Add aor 0: not-run
Sub sbr-zero 0: not-run
Sub aor 0: not-run
Unused sbr-zero 0: no-coverage
Unused aor 0: no-coverage
`, "no mutant runs")
			assert.Equal(t, rec.Mutants[0].Reason, cancelledReason, "the record states that the caller ended the run")
		})

		t.Run("states the load error of a package that does not type-check", func(t *testing.T) {
			t.Parallel()
			rec := runIn(t, module(t, map[string]string{arithFile: "package fixture\n\nvar V int = \"x\"\n"}),
				run.Config{})
			assert.Equal(t, codes(rec), []spec.ErrorCode{spec.ErrorLoad}, "the package does not load")
			assert.Empty(t, rec.Mutants, "a package that does not load has no mutant")
			assert.Nil(t, rec.Score, "a run with a run error has no score")
		})

		t.Run("names a package that does not load by its import path", func(t *testing.T) {
			t.Parallel()
			dir := module(t, map[string]string{arithFile: "package fixture\n\nimport _ \"fixture/missing\"\n"})
			rec := runIn(t, dir, run.Config{})
			assert.Equal(t, codes(rec), []spec.ErrorCode{spec.ErrorLoad}, "the package does not load")
			assert.Equal(t, rec.Target.Name, "fixture", "the target is the package's import path")
			root, err := filepath.EvalSymlinks(dir)
			assert.NoError(t, err, "the module's directory resolves")
			assert.Equal(t, rec.Root, root, "the root is the module's directory")
		})

		t.Run("states the load error of a package of the suite that does not list", func(t *testing.T) {
			t.Parallel()
			dir := module(t, with(scale, map[string]string{"broken/broken.go": "pkg broken\n"}))
			rec := runIn(t, dir, run.Config{Suite: []string{"./broken"}})
			assert.Equal(t, codes(rec), []spec.ErrorCode{spec.ErrorLoad}, "the suite does not load")
			assert.Equal(t, verdicts(rec), "Scale sbr-zero 0: not-run\nScale aor 0: not-run\n", "no mutant runs")
			assert.Equal(t, rec.Mutants[0].Reason, "the packages of the suite do not load",
				"the record states why no mutant runs")
		})

		t.Run("states an annotation error and runs no mutant", func(t *testing.T) {
			t.Parallel()
			dir := module(t, with(arithFiles, map[string]string{
				arithFile: strings.Replace(arith, "func Sub", fmt.Sprintf("%s %s: nothing to skip\nfunc Sub",
					annotation, spec.RORBoundary), 1),
			}))
			rec := runIn(t, dir, run.Config{})
			assert.Equal(t, codes(rec), []spec.ErrorCode{spec.ErrorStale}, "the annotation suppresses nothing")
			assert.Equal(t, verdicts(rec), arithNotRun, "no mutant runs")
			assert.Equal(t, rec.Mutants[0].Reason, "the run stopped at an annotation error",
				"the record states why no mutant runs")
		})

		t.Run("returns an error when the package directory does not read", func(t *testing.T) {
			t.Parallel()
			_, err := run.Run(t.Context(), run.Config{Dir: filepath.Join(t.TempDir(), missing), Env: os.Environ()})
			assert.ErrorIs(t, err, fs.ErrNotExist, "the directory does not exist")
			assert.HasPrefix(t, err.Error(), errorPrefix, "the error starts with the package's name")
		})
	})
}

// TestRunEnv sets TMPDIR, the state of the whole process, so neither it nor
// its subtests run in parallel.
func TestRunEnv(t *testing.T) {
	t.Run("Run", func(t *testing.T) {
		t.Run("returns an error when the work directory cannot be made", func(t *testing.T) {
			t.Setenv(tmpVar, filepath.Join(t.TempDir(), missing))
			_, err := run.Run(t.Context(), run.Config{Dir: ".", Env: os.Environ()})
			assert.ErrorIs(t, err, fs.ErrNotExist, "the temporary directory does not exist")
			assert.HasPrefix(t, err.Error(), errorPrefix, "the error starts with the package's name")
		})
	})
}
