// Copyright ThesmOS B.V. 2026
// SPDX-License-Identifier: MIT

package load_test

import (
	"context"
	"encoding/json"
	"fmt"
	"go/ast"
	"go/parser"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"go.dokimi.dev/mutate/internal/load"
)

// resolved returns dir with its symbolic links resolved.
func resolved(t *testing.T, dir string) string {
	t.Helper()
	dir, err := filepath.EvalSymlinks(dir)
	if err != nil {
		t.Fatal(err)
	}
	return dir
}

// roles lists each file's role and name, one per line.
func roles(p *load.Package) string {
	var b strings.Builder
	for _, f := range p.Files {
		fmt.Fprintf(&b, "%d %s\n", f.Role, f.Name)
	}
	return b.String()
}

// fakeEnv writes the env.json of a fake go command whose version is the
// engine's own.
func fakeEnv(t *testing.T, dir string) {
	t.Helper()
	write(
		t,
		dir,
		"env.json",
		`{"GOVERSION": "`+runtime.Version()+`", "GOMODCACHE": "/nonexistent", "GOARCH": "`+runtime.GOARCH+`"}`,
	)
}

// fakeList writes the list.json of a fake go command: the entries in the
// order given, each encoded as go list encodes it.
func fakeList(t *testing.T, dir string, entries ...map[string]any) {
	t.Helper()
	var b strings.Builder
	for _, e := range entries {
		data, err := json.Marshal(e)
		if err != nil {
			t.Fatal(err)
		}
		b.Write(data)
		b.WriteByte('\n')
	}
	write(t, dir, "list.json", b.String())
}

func TestLoad(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	t.Run("Load", func(t *testing.T) {
		t.Parallel()
		t.Run("type-checks the package and gives each compiled file its role", func(t *testing.T) {
			t.Parallel()
			dir := module(t, map[string]string{
				"a.go":       "package fixture\n\nfunc Add(a, b int) int { return a + b }\n",
				"gen.go":     "// Code generated by hand. DO NOT EDIT.\n\npackage fixture\n\nfunc twice(x int) int { return x * 2 }\n",
				"ignored.go": "//go:build ignore\n\npackage fixture\n\nfunc ignored() {}\n",
				"a_test.go":  "package fixture\n\nfunc helper() {}\n",
			})
			p, err := load.Load(ctx, load.Config{Dir: dir, Env: os.Environ()})
			if err != nil {
				t.Fatal(err)
			}
			dir = resolved(t, dir)
			if p.ImportPath != "fixture" || p.Name != "fixture" || p.Dir != dir || p.Root != dir || p.Language != 21 ||
				p.Toolchain != runtime.Version() {
				t.Errorf(
					"Load() = %q named %q in %s under %s at go1.%d by %s, want fixture named fixture in %s under %[7]s at go1.21 by %s",
					p.ImportPath,
					p.Name,
					p.Dir,
					p.Root,
					p.Language,
					p.Toolchain,
					dir,
					runtime.Version(),
				)
			}
			if got, want := roles(p), "0 a.go\n1 gen.go\n"; got != want {
				t.Errorf("roles:\n%s\nwant:\n%s", got, want)
			}
			if !p.Tests {
				t.Error("Tests = false, want true for a package with a_test.go")
			}
			if p.Files[0].Path != filepath.Join(dir, "a.go") ||
				string(p.Files[0].Text) != "package fixture\n\nfunc Add(a, b int) int { return a + b }\n" {
				t.Errorf("Files[0] reads %s: %q", p.Files[0].Path, p.Files[0].Text)
			}
			ret := p.Files[0].Syntax.Decls[0].(*ast.FuncDecl).Body.List[0].(*ast.ReturnStmt)
			if typ := p.Info.TypeOf(
				ret.Results[0],
			); p.Types.Name() != "fixture" || typ == nil ||
				typ.String() != "int" {
				t.Errorf("package %v, a + b has type %v, want package fixture and type int", p.Types, typ)
			}
		})
		t.Run("resolves a symbolic link in the directory", func(t *testing.T) {
			t.Parallel()
			dir := module(t, map[string]string{"a.go": "package fixture\n"})
			link := filepath.Join(t.TempDir(), "link")
			if err := os.Symlink(dir, link); err != nil {
				t.Fatal(err)
			}
			p, err := load.Load(ctx, load.Config{Dir: link, Env: os.Environ()})
			if err != nil {
				t.Fatal(err)
			}
			if dir = resolved(t, dir); p.Dir != dir || p.Files[0].Path != filepath.Join(dir, "a.go") {
				t.Errorf("Dir = %s and Files[0].Path = %s, want both in %s", p.Dir, p.Files[0].Path, dir)
			}
		})
		t.Run("names a file relative to the module root", func(t *testing.T) {
			t.Parallel()
			dir := module(t, map[string]string{"sub/a.go": "package sub\n"})
			p, err := load.Load(ctx, load.Config{Dir: filepath.Join(dir, "sub"), Env: os.Environ()})
			if err != nil {
				t.Fatal(err)
			}
			if p.ImportPath != "fixture/sub" || p.Root != resolved(t, dir) || p.Files[0].Name != "sub/a.go" {
				t.Errorf(
					"Load() = %s under %s with file %s, want fixture/sub under the module with file sub/a.go",
					p.ImportPath,
					p.Root,
					p.Files[0].Name,
				)
			}
		})
		t.Run("reads the language version from the go line", func(t *testing.T) {
			t.Parallel()
			tests := []struct {
				give string
				want int
			}{
				{"module fixture\n\ngo 1.10\n", 10},
				{"module fixture\n\ngo 1.21.0\n", 21},
				{"module fixture\n\ngo 1.21rc1\n", 21},
				{"module fixture\n", 16},
			}
			for _, tt := range tests {
				tt := tt
				t.Run(strings.ReplaceAll(tt.give, "\n", " "), func(t *testing.T) {
					t.Parallel()
					dir := module(t, map[string]string{"go.mod": tt.give, "a.go": "package fixture\n"})
					p, err := load.Load(ctx, load.Config{Dir: dir, Env: os.Environ()})
					if err != nil {
						t.Fatal(err)
					}
					if p.Language != tt.want {
						t.Errorf("Language = %d, want %d", p.Language, tt.want)
					}
				})
			}
		})
		t.Run("returns language 0 and the package directory as root outside a module", func(t *testing.T) {
			t.Parallel()
			gopath := t.TempDir()
			dir := filepath.Join(gopath, "src", "legacy")
			if err := os.MkdirAll(filepath.Join(dir, "vendor", "dep"), 0o755); err != nil {
				t.Fatal(err)
			}
			write(t, filepath.Join(dir, "vendor", "dep"), "d.go", "package dep\n\nconst One = 1\n")
			write(t, dir, "a.go", "package legacy\n\nimport \"dep\"\n\nfunc F(a int) int { return a + dep.One }\n")
			env := append(os.Environ(), "GO111MODULE=off", "GOPATH="+gopath)
			p, err := load.Load(ctx, load.Config{Dir: dir, Env: env})
			if err != nil {
				t.Fatal(err)
			}
			if dir = resolved(
				t,
				dir,
			); p.ImportPath != "legacy" || p.Language != 0 || p.Root != dir || p.Files[0].Name != "a.go" ||
				p.Tests {
				t.Errorf(
					"Load() = %s at go1.%d under %s with file %s and tests %v, want legacy at go1.0 under %s with file a.go and no tests",
					p.ImportPath,
					p.Language,
					p.Root,
					p.Files[0].Name,
					p.Tests,
					dir,
				)
			}
		})
		t.Run("gives cgo's rewrite of a file that imports C the role Cgo", func(t *testing.T) {
			t.Parallel()
			dir := module(t, map[string]string{
				"c.go": "package fixture\n\n// int twice(int x) { return 2 * x; }\nimport \"C\"\n\nfunc Twice(x int) int {\n\treturn int(C.twice(C.int(x))) + 1\n}\n",
				"g.go": "package fixture\n\nfunc Plain(x int) bool { return x > 2 }\n",
			})
			p, err := load.Load(ctx, load.Config{Dir: dir, Env: os.Environ()})
			if err != nil {
				t.Fatal(err)
			}
			var cgo *load.File
			for _, f := range p.Files {
				switch {
				case f.Role == load.Cgo:
					cgo = f
				case f.Role == load.Support && f.Name != "":
					t.Errorf("a support file has the name %s", f.Name)
				}
			}
			if got := p.Files[0]; got.Role != load.Source || got.Name != "g.go" {
				t.Errorf("Files[0] is %s with role %d, want g.go with role Source", got.Name, got.Role)
			}
			if cgo == nil || cgo.Name != "c.go" || cgo.Path == filepath.Join(resolved(t, dir), "c.go") {
				t.Fatalf("the cgo file is %+v, want the rewrite of c.go", cgo)
			}
			if pos := p.Fset.Position(
				cgo.Syntax.Package,
			); pos.Filename != filepath.Join(resolved(t, dir), "c.go") ||
				pos.Line != 1 {
				t.Errorf("the rewrite's package clause is at %s, want c.go:1", pos)
			}
		})
		t.Run("gives a generated file that imports C the role Generated", func(t *testing.T) {
			t.Parallel()
			dir := module(t, map[string]string{
				"c.go": "// Code generated by hand. DO NOT EDIT.\n\npackage fixture\n\nimport \"C\"\n\nfunc One() int { return 1 }\n",
			})
			p, err := load.Load(ctx, load.Config{Dir: dir, Env: os.Environ()})
			if err != nil {
				t.Fatal(err)
			}
			for _, f := range p.Files {
				if f.Role == load.Cgo {
					t.Errorf("%s has the role Cgo, want Generated", f.Name)
				}
			}
			if !strings.Contains(roles(p), "1 c.go\n") {
				t.Errorf("roles:\n%s\nwant c.go with the role Generated", roles(p))
			}
		})
		t.Run("gives a generated file whose header contains the include line the role of its kind", func(t *testing.T) {
			t.Parallel()
			header := "// Code generated by codecgen. DO NOT EDIT.\n//dokimi:mutate-include\n\npackage fixture\n\n"
			dir := module(t, map[string]string{
				"a.go": header + "func One() int { return 1 }\n",
				"b.go": "// Code generated by codecgen. DO NOT EDIT.\n\npackage fixture\n\n//dokimi:mutate-include\nfunc Two() int { return 2 }\n",
				"c.go": header + "import \"C\"\n\nfunc Three() int { return 3 }\n",
				"d.go": "// Code generated by codecgen. DO NOT EDIT.\n\n// Package fixture is generated.\npackage fixture\n\nfunc Four() int { return 4 }\n",
			})
			p, err := load.Load(ctx, load.Config{Dir: dir, Env: os.Environ(), Include: "//dokimi:mutate-include"})
			if err != nil {
				t.Fatal(err)
			}
			got := map[string]load.Role{}
			for _, f := range p.Files {
				if f.Name != "" {
					got[f.Name] = f.Role
				}
			}
			want := map[string]load.Role{
				"a.go": load.Source,
				"b.go": load.Generated,
				"c.go": load.Cgo,
				"d.go": load.Generated,
			}
			if fmt.Sprint(got) != fmt.Sprint(want) {
				t.Errorf("roles %v, want %v", got, want)
			}
		})
	})
	t.Run("Check", func(t *testing.T) {
		t.Parallel()
		// variant loads a package that imports strings, with the extra
		// imports, and parses text as a file of it.
		variant := func(t *testing.T, text string, imports ...string) (*load.Package, []*ast.File) {
			t.Helper()
			dir := module(
				t,
				map[string]string{"a.go": "package fixture\n\nimport \"strings\"\n\nvar Upper = strings.ToUpper\n"},
			)
			p, err := load.Load(ctx, load.Config{Dir: dir, Env: os.Environ(), Imports: imports})
			if err != nil {
				t.Fatal(err)
			}
			f, err := parser.ParseFile(p.Fset, filepath.Join(p.Dir, "a.go"), text, parser.ParseComments)
			if err != nil {
				t.Fatal(err)
			}
			return p, []*ast.File{f}
		}
		t.Run("returns no error for files that type-check", func(t *testing.T) {
			t.Parallel()
			p, files := variant(t, "package fixture\n\nimport \"strings\"\n\nvar Upper = strings.ToLower\n")
			if errs := p.Check(files, 0); len(errs) != 0 {
				t.Errorf("Check() = %v, want no error", errs)
			}
		})
		t.Run("returns each error with its position", func(t *testing.T) {
			t.Parallel()
			p, files := variant(t, "package fixture\n\nimport \"strings\"\n\nvar Upper int = strings.ToUpper(\"x\")\n")
			errs := p.Check(files, 0)
			if len(errs) != 1 || !strings.Contains(errs[0].Msg, "cannot use") ||
				p.Fset.Position(errs[0].Pos).Line != 5 {
				t.Errorf("Check() = %v, want one error on line 5", errs)
			}
		})
		t.Run("reads the export data of the imports that the configuration adds", func(t *testing.T) {
			t.Parallel()
			text := "package fixture\n\nimport \"strconv\"\n\nvar Upper = strconv.Itoa\n"
			p, files := variant(t, text, "strconv")
			if errs := p.Check(files, 0); len(errs) != 0 {
				t.Errorf("Check() with strconv added = %v, want no error", errs)
			}
			p, files = variant(t, text)
			if errs := p.Check(files, 0); len(errs) == 0 || !strings.Contains(errs[0].Msg, "could not import strconv") {
				t.Errorf("Check() without strconv added = %v, want an error that names strconv", errs)
			}
		})
		t.Run("checks at the language version it is given", func(t *testing.T) {
			t.Parallel()
			p, files := variant(t, "package fixture\n\nfunc id[T any](x T) T { return x }\n")
			if errs := p.Check(files, 17); len(errs) == 0 || !strings.Contains(errs[0].Msg, "go1.18") {
				t.Errorf("Check(go1.17) = %v, want an error that requires go1.18", errs)
			}
			if errs := p.Check(files, 18); len(errs) != 0 {
				t.Errorf("Check(go1.18) = %v, want no error", errs)
			}
		})
	})
	t.Run("Load errors", func(t *testing.T) {
		t.Parallel()
		tests := []struct {
			name string
			give func(t *testing.T) load.Config
			want string
		}{
			{"returns an error for a directory that does not exist", func(t *testing.T) load.Config {
				t.Helper()
				return load.Config{Dir: filepath.Join(t.TempDir(), "missing"), Env: os.Environ()}
			}, "no such file or directory"},
			{"returns an error when PATH names no go command", func(t *testing.T) load.Config {
				t.Helper()
				return load.Config{
					Dir: module(t, map[string]string{"a.go": "package fixture\n"}),
					Env: withPath(os.Environ(), t.TempDir()),
				}
			}, "no go command in the directories of PATH"},
			{"returns an error when go env prints no JSON", func(t *testing.T) load.Config {
				t.Helper()
				env, fake := fakeGo(t)
				write(t, fake, "env.json", "GOVERSION=go1")
				return load.Config{Dir: t.TempDir(), Env: env}
			}, "go env: invalid character"},
			{
				"returns an error when the go command's version differs from the engine's",
				func(t *testing.T) load.Config {
					t.Helper()
					env, fake := fakeGo(t)
					write(t, fake, "env.json", `{"GOVERSION": "go1.0.0"}`)
					return load.Config{Dir: t.TempDir(), Env: env}
				},
				"the go command is go1.0.0 and the engine was built by " + runtime.Version(),
			},
			{"returns an error for a package in the module cache", func(t *testing.T) load.Config {
				t.Helper()
				dir := module(t, map[string]string{"a.go": "package fixture\n"})
				return load.Config{Dir: dir, Env: append(os.Environ(), "GOMODCACHE="+filepath.Dir(dir))}
			}, "is in the module cache"},
			{"returns an error when go list fails", func(t *testing.T) load.Config {
				t.Helper()
				env, fake := fakeGo(t)
				fakeEnv(t, fake)
				return load.Config{Dir: t.TempDir(), Env: env}
			}, "go list -e"},
			{"returns an error when go list prints no JSON", func(t *testing.T) load.Config {
				t.Helper()
				env, fake := fakeGo(t)
				fakeEnv(t, fake)
				write(t, fake, "list.json", "{")
				return load.Config{Dir: t.TempDir(), Env: env}
			}, "go list: unexpected EOF"},
			{"returns an error when go list lists no package", func(t *testing.T) load.Config {
				t.Helper()
				env, fake := fakeGo(t)
				fakeEnv(t, fake)
				write(t, fake, "list.json", "")
				return load.Config{Dir: t.TempDir(), Env: env}
			}, "go list lists no package in "},
			{"returns an error for a package that does not type-check", func(t *testing.T) load.Config {
				t.Helper()
				return load.Config{
					Dir: module(t, map[string]string{"a.go": "package fixture\n\nfunc F() int { return \"x\" }\n"}),
					Env: os.Environ(),
				}
			}, `cannot use "x"`},
			{"returns an error for a dependency that does not build", func(t *testing.T) load.Config {
				t.Helper()
				dir := module(t, map[string]string{
					"a.go":     "package fixture\n\nimport \"fixture/dep\"\n\nvar V = dep.V\n",
					"dep/d.go": "package dep\n\nvar V int = \"x\"\n",
				})
				return load.Config{Dir: dir, Env: os.Environ()}
			}, `cannot use "x"`},
			{"returns an error when go list lists no package in the directory", func(t *testing.T) load.Config {
				t.Helper()
				env, fake := fakeGo(t)
				fakeEnv(t, fake)
				fakeList(t, fake, map[string]any{"ImportPath": "fixture", "Name": "fixture", "Dir": t.TempDir()})
				return load.Config{Dir: t.TempDir(), Env: env}
			}, "go list lists no package in "},
			{"returns an error when a compiled file does not exist", func(t *testing.T) load.Config {
				t.Helper()
				env, fake := fakeGo(t)
				fakeEnv(t, fake)
				dir := resolved(t, t.TempDir())
				fakeList(
					t,
					fake,
					map[string]any{
						"ImportPath":      "fixture",
						"Name":            "fixture",
						"Dir":             dir,
						"GoFiles":         []string{"a.go"},
						"CompiledGoFiles": []string{"a.go"},
					},
				)
				return load.Config{Dir: dir, Env: env}
			}, "no such file or directory"},
			{"returns an error when a compiled file does not parse", func(t *testing.T) load.Config {
				t.Helper()
				env, fake := fakeGo(t)
				fakeEnv(t, fake)
				dir := resolved(t, module(t, map[string]string{"a.go": "package fixture\n\nfunc {\n"}))
				fakeList(
					t,
					fake,
					map[string]any{
						"ImportPath":      "fixture",
						"Name":            "fixture",
						"Dir":             dir,
						"GoFiles":         []string{"a.go"},
						"CompiledGoFiles": []string{"a.go"},
					},
				)
				return load.Config{Dir: dir, Env: env}
			}, "expected"},
			{"returns an error when a dependency has no export data", func(t *testing.T) load.Config {
				t.Helper()
				env, fake := fakeGo(t)
				fakeEnv(t, fake)
				dir := resolved(
					t,
					module(t, map[string]string{"a.go": "package fixture\n\nimport \"fmt\"\n\nvar _ = fmt.Sprint\n"}),
				)
				fakeList(
					t,
					fake,
					map[string]any{"ImportPath": "fmt", "DepOnly": true},
					map[string]any{
						"ImportPath":      "fixture",
						"Name":            "fixture",
						"Dir":             dir,
						"GoFiles":         []string{"a.go"},
						"CompiledGoFiles": []string{"a.go"},
					},
				)
				return load.Config{Dir: dir, Env: env}
			}, `no export data for "fmt"`},
			{"returns an error when the file that a cgo rewrite names does not exist", func(t *testing.T) load.Config {
				t.Helper()
				env, fake := fakeGo(t)
				fakeEnv(t, fake)
				dir := resolved(t, t.TempDir())
				rewrite := filepath.Join(t.TempDir(), "c.cgo1.go")
				write(
					t,
					filepath.Dir(rewrite),
					"c.cgo1.go",
					"//line "+filepath.Join(dir, "c.go")+":1:1\npackage fixture\n",
				)
				fakeList(
					t,
					fake,
					map[string]any{
						"ImportPath":      "fixture",
						"Name":            "fixture",
						"Dir":             dir,
						"CgoFiles":        []string{"c.go"},
						"CompiledGoFiles": []string{rewrite},
					},
				)
				return load.Config{Dir: dir, Env: env}
			}, "no such file or directory"},
			{"returns an error when a file lies outside the module root", func(t *testing.T) load.Config {
				t.Helper()
				env, fake := fakeGo(t)
				fakeEnv(t, fake)
				dir := resolved(t, module(t, map[string]string{"a.go": "package fixture\n"}))
				fakeList(
					t,
					fake,
					map[string]any{
						"ImportPath":      "fixture",
						"Name":            "fixture",
						"Dir":             dir,
						"GoFiles":         []string{"a.go"},
						"CompiledGoFiles": []string{"a.go"},
						"Module":          map[string]string{"Dir": "relative"},
					},
				)
				return load.Config{Dir: dir, Env: env}
			}, "can't make"},
		}
		for _, tt := range tests {
			tt := tt
			t.Run(tt.name, func(t *testing.T) {
				t.Parallel()
				_, err := load.Load(ctx, tt.give(t))
				if err == nil || !strings.Contains(err.Error(), tt.want) || strings.HasPrefix(err.Error(), "load") {
					t.Errorf("Load() error = %v, want one that contains %q and does not start with load", err, tt.want)
				}
			})
		}
		t.Run("states each error that go list reports once", func(t *testing.T) {
			t.Parallel()
			// go list -deps reports the missing package's error, and the same
			// text again among the importer's errors of its dependencies.
			dir := module(t, map[string]string{"a.go": "package fixture\n\nimport _ \"fixture/missing\"\n"})
			_, err := load.Load(ctx, load.Config{Dir: dir, Env: os.Environ()})
			if err == nil || strings.Count(err.Error(), "package fixture/missing is not in ") != 1 {
				t.Errorf("Load() error = %v, want the error of fixture/missing once", err)
			}
		})
		tests = []struct {
			name string
			give func(t *testing.T) load.Config
			want string
		}{
			{"returns the package that go list lists with the error of a dependency", func(t *testing.T) load.Config {
				t.Helper()
				return load.Config{
					Dir: module(t, map[string]string{"a.go": "package fixture\n\nimport _ \"fixture/missing\"\n"}),
					Env: os.Environ(),
				}
			}, "package fixture/missing is not in "},
			{"returns the package that go list lists with its type error", func(t *testing.T) load.Config {
				t.Helper()
				return load.Config{
					Dir: module(t, map[string]string{"a.go": "package fixture\n\nvar V int = \"x\"\n"}),
					Env: os.Environ(),
				}
			}, `cannot use "x"`},
		}
		for _, tt := range tests {
			tt := tt
			t.Run(tt.name, func(t *testing.T) {
				t.Parallel()
				cfg := tt.give(t)
				p, err := load.Load(ctx, cfg)
				if p == nil {
					t.Fatalf("Load() returns no package with the error %v", err)
				}
				if dir := resolved(t, cfg.Dir); err == nil || !strings.Contains(err.Error(), tt.want) ||
					p.ImportPath != "fixture" || p.Root != dir {
					t.Errorf(
						"Load() = %s under %s with the error %v, want fixture under %s with an error that contains %q",
						p.ImportPath,
						p.Root,
						err,
						dir,
						tt.want,
					)
				}
			})
		}
	})
}
