// Copyright ThesmOS B.V. 2026
// SPDX-License-Identifier: MIT

package load_test

import (
	"context"
	"fmt"
	"go/ast"
	"go/parser"
	"maps"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"go.dokimi.dev/assert"
	"go.dokimi.dev/assert/expect"

	"go.dokimi.dev/mutate/internal/load"
)

// include is the include directive that the tests pass to Load.
const include = "//dokimi:mutate-include"

// roles lists each file's role, whether it is generated, and its name, one
// file per line.
func roles(p *load.Package) string {
	var b strings.Builder
	for _, f := range p.Files {
		fmt.Fprintf(&b, "%d %t %s\n", f.Role, f.Generated, f.Name)
	}
	return b.String()
}

// listedFixture writes the list.json of a fake go command that lists the
// package fixture in dir with the compiled file a.go, and the entries of
// more before it.
func listedFixture(t *testing.T, fake, dir string, fields map[string]any, more ...map[string]any) {
	t.Helper()
	entry := map[string]any{
		"ImportPath": "fixture", "Name": "fixture", "Dir": dir,
		"GoFiles": []string{"a.go"}, "CompiledGoFiles": []string{"a.go"},
	}
	maps.Copy(entry, fields)
	fakeList(t, fake, append(more, entry)...)
}

func TestLoad(t *testing.T) {
	t.Parallel()
	ctx := context.Background()

	t.Run("Load", func(t *testing.T) {
		t.Parallel()

		t.Run("type-checks the package and gives each compiled file its role", func(t *testing.T) {
			t.Parallel()
			dir := resolved(t, moduleDir(t, map[string]string{
				"a.go":       "package fixture\n\nfunc Add(a, b int) int { return a + b }\n",
				"gen.go":     "// Code generated by hand. DO NOT EDIT.\n\npackage fixture\n\nfunc twice(x int) int { return x * 2 }\n",
				"ignored.go": "//go:build ignore\n\npackage fixture\n\nfunc ignored() {}\n",
				"a_test.go":  "package fixture\n\nfunc helper() {}\n",
			}))
			p, err := load.Load(ctx, load.Config{Dir: dir, Env: os.Environ()})
			assert.NoError(t, err, "the package loads")
			expect.Equal(t, p.ImportPath, "fixture", "the package has the module's path")
			expect.Equal(t, p.Name, "fixture", "and the package clause's name")
			expect.Equal(t, p.Dir, dir, "and its directory")
			expect.Equal(t, p.Root, dir, "and the module's directory as its root")
			expect.Equal(t, p.Language, 21, "and the go line's language version")
			expect.Equal(t, p.Toolchain, runtime.Version(), "and the go command's version")
			expect.True(t, p.Tests, "a_test.go is a test file")
			expect.Equal(t, roles(p), "0 false a.go\n0 true gen.go\n",
				"the compiled files are the package's own, and gen.go is generated")
			assert.NotEmpty(t, p.Files, "the package has compiled files")
			expect.Equal(t, p.Files[0].Path, filepath.Join(dir, "a.go"), "a file states its path")
			expect.Equal(t, string(p.Files[0].Text), "package fixture\n\nfunc Add(a, b int) int { return a + b }\n",
				"and its text")
			ret := p.Files[0].Syntax.Decls[0].(*ast.FuncDecl).Body.List[0].(*ast.ReturnStmt)
			expect.Equal(t, p.Types.Name(), "fixture", "the type checker names the package")
			expect.Equal(t, p.Info.TypeOf(ret.Results[0]).String(), "int", "and states the type of a + b")
		})

		t.Run("resolves a symbolic link in the directory", func(t *testing.T) {
			t.Parallel()
			dir := moduleDir(t, map[string]string{"a.go": "package fixture\n"})
			link := filepath.Join(t.TempDir(), "link")
			assert.NoError(t, os.Symlink(dir, link), "the link is created")
			p, err := load.Load(ctx, load.Config{Dir: link, Env: os.Environ()})
			assert.NoError(t, err, "the package loads through the link")
			dir = resolved(t, dir)
			expect.Equal(t, p.Dir, dir, "the directory is the link's target")
			expect.Equal(t, p.Files[0].Path, filepath.Join(dir, "a.go"), "and so is every file's path")
		})

		t.Run("names a file relative to the module root", func(t *testing.T) {
			t.Parallel()
			dir := moduleDir(t, map[string]string{"sub/a.go": "package sub\n"})
			p, err := load.Load(ctx, load.Config{Dir: filepath.Join(dir, "sub"), Env: os.Environ()})
			assert.NoError(t, err, "the package loads")
			expect.Equal(t, p.ImportPath, "fixture/sub", "the package has its import path")
			expect.Equal(t, p.Root, resolved(t, dir), "and the module's directory as its root")
			expect.Equal(t, p.Files[0].Name, "sub/a.go", "and its file's name starts at the root")
		})

		languages := []struct {
			name string
			give string
			want int
		}{
			{"returns the minor version of a go line of two numbers", "module fixture\n\ngo 1.10\n", 10},
			{"returns the minor version of a go line with a patch release", "module fixture\n\ngo 1.21.0\n", 21},
			{"returns the minor version of a go line of a release candidate", "module fixture\n\ngo 1.21rc1\n", 21},
			{"returns 16 for a module without a go line", "module fixture\n", 16},
		}
		for _, tt := range languages {
			t.Run(tt.name, func(t *testing.T) {
				t.Parallel()
				dir := moduleDir(t, map[string]string{goMod: tt.give, "a.go": "package fixture\n"})
				p, err := load.Load(ctx, load.Config{Dir: dir, Env: os.Environ()})
				assert.NoError(t, err, "the package loads")
				assert.Equal(t, p.Language, tt.want, "Language is the go line's minor version")
			})
		}

		t.Run("returns language 0 and the package directory as root outside a module", func(t *testing.T) {
			t.Parallel()
			gopath := t.TempDir()
			dir := filepath.Join(gopath, "src", "legacy")
			write(t, dir, "vendor/dep/d.go", "package dep\n\nconst One = 1\n")
			write(t, dir, "a.go", "package legacy\n\nimport \"dep\"\n\nfunc F(a int) int { return a + dep.One }\n")
			env := append(os.Environ(), "GO111MODULE=off", "GOPATH="+gopath)
			p, err := load.Load(ctx, load.Config{Dir: dir, Env: env})
			assert.NoError(t, err, "a package of GOPATH loads")
			dir = resolved(t, dir)
			expect.Equal(t, p.ImportPath, "legacy", "the package has its path below GOPATH")
			expect.Equal(t, p.Language, 0, "and the toolchain's language version")
			expect.Equal(t, p.Root, dir, "and its own directory as its root")
			expect.Equal(t, p.Files[0].Name, "a.go", "and its file's name starts there")
			expect.False(t, p.Tests, "and it has no test file")
		})

		t.Run("gives cgo's rewrite of a file that imports C the role Cgo", func(t *testing.T) {
			t.Parallel()
			dir := resolved(t, moduleDir(t, map[string]string{
				"c.go": "package fixture\n\n// int twice(int x) { return 2 * x; }\nimport \"C\"\n\n" +
					"func Twice(x int) int {\n\treturn int(C.twice(C.int(x))) + 1\n}\n",
				"g.go": "package fixture\n\nfunc Plain(x int) bool { return x > 2 }\n",
			}))
			p, err := load.Load(ctx, load.Config{Dir: dir, Env: os.Environ()})
			assert.NoError(t, err, "a package that imports C loads")
			expect.Equal(t, p.Files[0].Role, load.Source, "g.go is the package's own")
			expect.Equal(t, p.Files[0].Name, "g.go", "and named after its source")
			var cgo *load.File
			for _, f := range p.Files[1:] {
				if f.Role == load.Cgo {
					cgo = f
				} else {
					expect.Equal(t, f.Name, "", "a support file has no name")
				}
			}
			assert.NotNil(t, cgo, "one file is cgo's rewrite")
			expect.Equal(t, cgo.Name, "c.go", "the rewrite is named after the file that imports C")
			expect.NotEqual(t, cgo.Path, filepath.Join(dir, "c.go"), "and is the rewrite's own file")
			pos := p.Fset.Position(cgo.Syntax.Package)
			expect.Equal(t, pos.Filename, filepath.Join(dir, "c.go"), "its line directives map it to c.go")
			expect.Equal(t, pos.Line, 1, "from the first line")
		})

		t.Run("marks cgo's rewrite of a generated file that imports C as generated", func(t *testing.T) {
			t.Parallel()
			dir := moduleDir(t, map[string]string{
				"c.go": "// Code generated by hand. DO NOT EDIT.\n\npackage fixture\n\nimport \"C\"\n\nfunc One() int { return 1 }\n",
			})
			p, err := load.Load(ctx, load.Config{Dir: dir, Env: os.Environ()})
			assert.NoError(t, err, "a generated package that imports C loads")
			assert.Contains(t, roles(p), "1 true c.go\n", "the rewrite of c.go is a generated Cgo file")
		})

		t.Run("marks a generated file generated unless a comment before its package clause is the include line",
			func(t *testing.T) {
				t.Parallel()
				header := "// Code generated by codecgen. DO NOT EDIT.\n" + include + "\n\npackage fixture\n\n"
				dir := moduleDir(t, map[string]string{
					"a.go": header + "func One() int { return 1 }\n",
					"b.go": "// Code generated by codecgen. DO NOT EDIT.\n\npackage fixture\n\n" + include +
						"\nfunc Two() int { return 2 }\n",
					"c.go": header + "import \"C\"\n\nfunc Three() int { return 3 }\n",
					"d.go": "// Code generated by codecgen. DO NOT EDIT.\n\n// Package fixture is generated.\npackage fixture\n\n" +
						"func Four() int { return 4 }\n",
				})
				p, err := load.Load(ctx, load.Config{Dir: dir, Env: os.Environ(), Include: include})
				assert.NoError(t, err, "the package loads")
				got := map[string]bool{}
				for _, f := range p.Files {
					if f.Name != "" {
						got[f.Name] = f.Generated
					}
				}
				assert.Equal(t, got, map[string]bool{"a.go": false, "b.go": true, "c.go": false, "d.go": true},
					"only the include line before the package clause makes a generated file a target")
			},
		)

		t.Run("returns each error that go list states once", func(t *testing.T) {
			t.Parallel()
			// go list -deps states the missing package's error, and the same
			// text again among the importer's errors of its dependencies.
			dir := moduleDir(t, map[string]string{"a.go": "package fixture\n\nimport _ \"fixture/missing\"\n"})
			_, err := load.Load(ctx, load.Config{Dir: dir, Env: os.Environ()})
			assert.HasError(t, err, "a missing dependency fails the load")
			assert.Equal(t, strings.Count(err.Error(), "package fixture/missing is not in "), 1,
				"the error states the missing package once")
		})

		partial := []struct {
			name string
			give string
			want string
		}{
			{
				"returns the package that go list lists with the error of a dependency",
				"package fixture\n\nimport _ \"fixture/missing\"\n",
				"package fixture/missing is not in ",
			},
			{
				"returns the package that go list lists with its type error",
				"package fixture\n\nvar V int = \"x\"\n",
				`cannot use "x"`,
			},
		}
		for _, tt := range partial {
			t.Run(tt.name, func(t *testing.T) {
				t.Parallel()
				dir := moduleDir(t, map[string]string{"a.go": tt.give})
				p, err := load.Load(ctx, load.Config{Dir: dir, Env: os.Environ()})
				assert.HasError(t, err, "the package does not load")
				assert.Contains(t, err.Error(), tt.want, "the error states the cause")
				assert.NotNil(t, p, "Load returns the package that go list lists")
				expect.Equal(t, p.ImportPath, "fixture", "with its import path")
				expect.Equal(t, p.Root, resolved(t, dir), "and its root")
			})
		}

		errs := []struct {
			name string
			give func(t *testing.T) load.Config
			want string
		}{
			{
				name: "returns an error for a directory that does not exist",
				give: func(t *testing.T) load.Config {
					t.Helper()
					return load.Config{Dir: filepath.Join(t.TempDir(), "missing"), Env: os.Environ()}
				},
				want: "no such file or directory",
			},
			{
				name: "returns an error when PATH names no go command",
				give: func(t *testing.T) load.Config {
					t.Helper()
					return load.Config{
						Dir: moduleDir(t, map[string]string{"a.go": "package fixture\n"}),
						Env: withPath(os.Environ(), t.TempDir()),
					}
				},
				want: "no go command in the directories of PATH",
			},
			{
				name: "returns an error when go env writes no JSON",
				give: func(t *testing.T) load.Config {
					t.Helper()
					env, fake := fakeGo(t)
					write(t, fake, envFile, "GOVERSION=go1")
					return load.Config{Dir: t.TempDir(), Env: env}
				},
				want: "go env: invalid character",
			},
			{
				name: "returns an error when the go command's version differs from the engine's",
				give: func(t *testing.T) load.Config {
					t.Helper()
					env, fake := fakeGo(t)
					write(t, fake, envFile, `{"GOVERSION": "go1.0.0"}`)
					return load.Config{Dir: t.TempDir(), Env: env}
				},
				want: "the go command is go1.0.0 and the engine was built by " + runtime.Version(),
			},
			{
				name: "returns an error for a package in the module cache",
				give: func(t *testing.T) load.Config {
					t.Helper()
					dir := moduleDir(t, map[string]string{"a.go": "package fixture\n"})
					return load.Config{Dir: dir, Env: append(os.Environ(), "GOMODCACHE="+filepath.Dir(dir))}
				},
				want: "is in the module cache",
			},
			{
				name: "returns an error when go list fails",
				give: func(t *testing.T) load.Config {
					t.Helper()
					env, fake := fakeGo(t)
					fakeEnv(t, fake)
					return load.Config{Dir: t.TempDir(), Env: env}
				},
				want: "go list -e -json=",
			},
			{
				name: "returns an error when an entry of go list does not decode",
				give: func(t *testing.T) load.Config {
					t.Helper()
					env, fake := fakeGo(t)
					fakeEnv(t, fake)
					write(t, fake, listFile, "{")
					return load.Config{Dir: t.TempDir(), Env: env}
				},
				want: "go list: unexpected EOF",
			},
			{
				name: "returns an error when go list lists no package",
				give: func(t *testing.T) load.Config {
					t.Helper()
					env, fake := fakeGo(t)
					fakeEnv(t, fake)
					write(t, fake, listFile, "")
					return load.Config{Dir: t.TempDir(), Env: env}
				},
				want: "go list lists no package in ",
			},
			{
				name: "returns an error when go list lists no package in the directory",
				give: func(t *testing.T) load.Config {
					t.Helper()
					env, fake := fakeGo(t)
					fakeEnv(t, fake)
					fakeList(t, fake, map[string]any{"ImportPath": "fixture", "Name": "fixture", "Dir": t.TempDir()})
					return load.Config{Dir: t.TempDir(), Env: env}
				},
				want: "go list lists no package in ",
			},
			{
				name: "returns an error for a package that does not type-check",
				give: func(t *testing.T) load.Config {
					t.Helper()
					return load.Config{
						Dir: moduleDir(
							t,
							map[string]string{"a.go": "package fixture\n\nfunc F() int { return \"x\" }\n"},
						),
						Env: os.Environ(),
					}
				},
				want: `cannot use "x"`,
			},
			{
				name: "returns an error for a dependency that does not build",
				give: func(t *testing.T) load.Config {
					t.Helper()
					dir := moduleDir(t, map[string]string{
						"a.go":     "package fixture\n\nimport \"fixture/dep\"\n\nvar V = dep.V\n",
						"dep/d.go": "package dep\n\nvar V int = \"x\"\n",
					})
					return load.Config{Dir: dir, Env: os.Environ()}
				},
				want: `cannot use "x"`,
			},
			{
				name: "returns an error when a compiled file does not exist",
				give: func(t *testing.T) load.Config {
					t.Helper()
					env, fake := fakeGo(t)
					fakeEnv(t, fake)
					dir := resolved(t, t.TempDir())
					listedFixture(t, fake, dir, nil)
					return load.Config{Dir: dir, Env: env}
				},
				want: "no such file or directory",
			},
			{
				name: "returns an error when a compiled file does not parse",
				give: func(t *testing.T) load.Config {
					t.Helper()
					env, fake := fakeGo(t)
					fakeEnv(t, fake)
					dir := resolved(t, moduleDir(t, map[string]string{"a.go": "package fixture\n\nfunc {\n"}))
					listedFixture(t, fake, dir, nil)
					return load.Config{Dir: dir, Env: env}
				},
				want: "expected",
			},
			{
				name: "returns an error when a dependency has no export data",
				give: func(t *testing.T) load.Config {
					t.Helper()
					env, fake := fakeGo(t)
					fakeEnv(t, fake)
					dir := resolved(
						t,
						moduleDir(
							t,
							map[string]string{"a.go": "package fixture\n\nimport \"fmt\"\n\nvar _ = fmt.Sprint\n"},
						),
					)
					listedFixture(t, fake, dir, nil, map[string]any{"ImportPath": "fmt", "DepOnly": true})
					return load.Config{Dir: dir, Env: env}
				},
				want: `no export data for "fmt"`,
			},
			{
				name: "returns an error when the file that a cgo rewrite names does not exist",
				give: func(t *testing.T) load.Config {
					t.Helper()
					env, fake := fakeGo(t)
					fakeEnv(t, fake)
					dir := resolved(t, t.TempDir())
					rewrite := filepath.Join(t.TempDir(), "c.cgo1.go")
					write(
						t,
						filepath.Dir(rewrite),
						"c.cgo1.go",
						"//line "+filepath.Join(dir, "c.go")+":1:1\npackage fixture\n",
					)
					listedFixture(t, fake, dir, map[string]any{
						"GoFiles": nil, "CgoFiles": []string{"c.go"}, "CompiledGoFiles": []string{rewrite},
					})
					return load.Config{Dir: dir, Env: env}
				},
				want: "no such file or directory",
			},
			{
				name: "returns an error when a file lies outside the module root",
				give: func(t *testing.T) load.Config {
					t.Helper()
					env, fake := fakeGo(t)
					fakeEnv(t, fake)
					dir := resolved(t, moduleDir(t, map[string]string{"a.go": "package fixture\n"}))
					listedFixture(t, fake, dir, map[string]any{"Module": map[string]string{"Dir": "relative"}})
					return load.Config{Dir: dir, Env: env}
				},
				want: "can't make",
			},
		}
		for _, tt := range errs {
			t.Run(tt.name, func(t *testing.T) {
				t.Parallel()
				_, err := load.Load(ctx, tt.give(t))
				assert.HasError(t, err, "Load fails")
				assert.Contains(t, err.Error(), tt.want, "the error states the cause")
				assert.False(t, strings.HasPrefix(err.Error(), "load"), "and does not start with the package's name")
			})
		}
	})

	t.Run("Check", func(t *testing.T) {
		t.Parallel()

		// variant loads a package that imports strings, with the extra
		// imports, and parses text as a file of it.
		variant := func(t *testing.T, text string, imports ...string) (*load.Package, []*ast.File) {
			t.Helper()
			dir := moduleDir(
				t,
				map[string]string{"a.go": "package fixture\n\nimport \"strings\"\n\nvar Upper = strings.ToUpper\n"},
			)
			p, err := load.Load(ctx, load.Config{Dir: dir, Env: os.Environ(), Imports: imports})
			assert.NoError(t, err, "the package loads")
			f, err := parser.ParseFile(p.Fset, filepath.Join(p.Dir, "a.go"), text, parser.ParseComments)
			assert.NoError(t, err, "the variant parses")
			return p, []*ast.File{f}
		}

		t.Run("returns no error for files that type-check", func(t *testing.T) {
			t.Parallel()
			p, files := variant(t, "package fixture\n\nimport \"strings\"\n\nvar Upper = strings.ToLower\n")
			assert.Empty(t, p.Check(files, 0), "the variant type-checks")
		})

		t.Run("returns each error with its position", func(t *testing.T) {
			t.Parallel()
			p, files := variant(t, "package fixture\n\nimport \"strings\"\n\nvar Upper int = strings.ToUpper(\"x\")\n")
			errs := p.Check(files, 0)
			assert.Length(t, errs, 1, "the variant has one error")
			expect.Contains(t, errs[0].Msg, "cannot use", "the error states the type mismatch")
			expect.Equal(t, p.Fset.Position(errs[0].Pos).Line, 5, "at its line")
		})

		t.Run("reads the export data of the imports that the configuration adds", func(t *testing.T) {
			t.Parallel()
			text := "package fixture\n\nimport \"strconv\"\n\nvar Upper = strconv.Itoa\n"
			p, files := variant(t, text, "strconv")
			assert.Empty(t, p.Check(files, 0), "a variant that imports an added package type-checks")
			p, files = variant(t, text)
			errs := p.Check(files, 0)
			assert.NotEmpty(t, errs, "without the added import the variant does not type-check")
			assert.Contains(t, errs[0].Msg, "could not import strconv", "the error names the import")
		})

		t.Run("checks at the language version it is given", func(t *testing.T) {
			t.Parallel()
			p, files := variant(t, "package fixture\n\nfunc id[T any](x T) T { return x }\n")
			errs := p.Check(files, 17)
			assert.NotEmpty(t, errs, "generics do not type-check at go1.17")
			assert.Contains(t, errs[0].Msg, "go1.18", "the error states the version that generics need")
			assert.Empty(t, p.Check(files, 18), "and they type-check at go1.18")
		})
	})
}
