// Copyright ThesmOS B.V. 2026
// SPDX-License-Identifier: MIT

// TestHelp writes this file from the help with -update. Edit the help in help.go.

// Command dokimi-mutate-go measures how well the tests of Go packages detect faults.
//
// The command changes each package's code in small, defined ways, such as
// a + b to a - b. Each change is a mutant. The command runs the package's
// tests against each mutant, one at a time. A mutant that no test detects is a
// gap in the tests. The command prints each such mutant at its file and line,
// and a mutation score for each package.
//
// Usage:
//
//	dokimi-mutate-go [flags] [packages]
//
// The packages are patterns, as go list resolves them. The default is the
// package in the current directory. The module under test needs no change:
//
//	go run go.dokimi.dev/mutate/cmd/dokimi-mutate-go@latest ./...
//
// Selection:
//
//	-lines file:first-last
//		Test only the mutants on lines first to last of file. The path
//		is relative to the current directory. The flag repeats.
//	-diff file
//		Test only the mutants on the lines that the unified diff in file
//		adds, and on the lines on either side of each run of removed
//		lines. A path after its b/ prefix is relative to the current
//		directory. The file - reads standard input.
//	-sample n
//		Test only the first n mutants of each package, in the order of
//		their keys. The same code gives the same sample on every
//		machine, and the score is the score of the sample.
//	-include-generated
//		Also mutate generated files. A generated file has a comment line
//		such as "// Code generated by stringer. DO NOT EDIT." before its
//		package clause. Without the flag, the command mutates such a
//		file only when the comments before its package clause contain
//		the line //dokimi:mutate-include.
//
// Tests:
//
//	-suite pattern
//		Also run the tests of the packages that pattern names against
//		each package's mutants, where those tests import the package.
//		The flag repeats.
//	-confirm
//		Test each mutant that survived or that no test covers once more,
//		in a normal build that contains this mutant alone. Tests that
//		skip in the instrumented build, such as allocation checks, then
//		run against it. Each such mutant costs one more build.
//
// Execution:
//
//	-C dir
//		Change to dir before the command resolves packages and paths.
//	-p n
//		The number of packages that may run at once. The default is 1.
//		Above 1, the command counts each package's mutants first, starts
//		the packages with the most mutants first, and gives each a share
//		of the command's GOMAXPROCS threads in proportion to its
//		mutants.
//	-workers n
//		The most mutants of one package to test at once. The default is
//		1. A package tests as many as its share of the threads allows,
//		and more, up to n, on the threads that other packages return.
//		Above 1, tests that share a resource, such as a fixed port, can
//		fail each other, and each such failure counts as a detection.
//	-timeout d
//		The time limit of the command, such as 30m. A mutant starts only
//		when it can finish before the limit. The mutants that do not
//		start fail the run, and the summary states the score of those
//		that ran. The default, 0, sets no limit.
//	-memory-budget size
//		The memory that the packages tested at once may use, such as
//		16G, with K, M, G or T for powers of 1024. A package starts its
//		mutants when its workers' memory ceilings fit in the budget
//		beside those of the running packages. The default is three
//		quarters of the memory that the process may use, by its cgroup
//		or by the machine. 0 sets no budget.
//
// Output:
//
//	-json
//		Write each package's record to standard output as one line of
//		JSON, in place of the text.
//	-record dir
//		Write each package's record to a file in dir.
//	-list
//		Print the mutants of each package, and run no test.
//	-version
//		Print the versions of the engine, the operator catalogue, the Go
//		overlay and the Go toolchain that built the engine.
//
// The command prints each mutant that survived or that no test covers when its
// verdict is final, and a summary when a package's run ends:
//
//	wire/codec.go:41:9: survived: n + 1 became n - 1 (aor)
//	wire/codec.go:52:2: not covered: buf.Reset() removed (sbr-delete)
//	example.com/wire: 410 of 432 mutants detected (94%): 405 killed, 5 timed out, 20 survived, 2 not covered
//
// Progress lines and errors go to standard error.
//
// Exit status:
//
//	0  Every counted mutant was detected, and every run completed.
//	1  A package has a mutant that survived or that no test covers, in
//	   its sample when -sample ended its run.
//	2  The command line or an input is invalid.
//	3  A run failed, such as a package that does not build, tests that
//	   fail without a mutant, or a run that -timeout ended. The command
//	   also exits with 3 when it cannot write to standard output.
//
// A test can read two variables. DOKIMI_MUTATE_MUTANT is 0 in the control runs
// and the active mutant's number in a mutant's run. DOKIMI_MUTATE_INSTRUMENTED
// is 1 in every run of the instrumented build. Skip an allocation or timing
// assertion while DOKIMI_MUTATE_INSTRUMENTED is set, and use -confirm.
//
// Examples:
//
//	dokimi-mutate-go ./...
//	git diff origin/main...HEAD | dokimi-mutate-go -diff - ./...
//	dokimi-mutate-go -workers 4 -timeout 30m -record out ./...
//	dokimi-mutate-go -list ./wire
package main
