// Copyright ThesmOS B.V. 2026
// SPDX-License-Identifier: MIT

package main

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"slices"
	"strconv"
	"strings"
	"testing"
	"time"

	"go.dokimi.dev/assert"

	"go.dokimi.dev/mutate/internal/record"
)

// usageLine ends the output of a command line that is not valid.
const usageLine = "Run '" + name + " -help' for usage.\n"

// generatedFile is a generated file of the package fixture, and
// generatedTest a test that checks its function.
const (
	generatedFile = "// Code generated by hand. DO NOT EDIT.\n\npackage fixture\n\nfunc Double(x int) int { return x * 2 }\n"
	generatedTest = `package fixture

import "testing"

func TestDouble(t *testing.T) {
	if Double(2) != 4 {
		t.Error("Double(2) != 4")
	}
}
`
)

// subProcsVar is the GOMAXPROCS that the package sub of the case of the
// threads expects.
const subProcsVar = "FIXTURE_SUB_PROCS"

// cancelling is a standard output that cancels the command's context at its
// first write.
type cancelling struct {
	bytes.Buffer
	cancel context.CancelFunc
}

// Write cancels the context and writes data.
func (c *cancelling) Write(data []byte) (int, error) {
	c.cancel()
	return c.Buffer.Write(data)
}

// errFull is the error of every write to full.
var errFull = errors.New("no space left on device")

// full is a standard output whose every write fails, as a write to a full
// device does.
type full struct{}

// Write writes nothing and returns errFull.
func (full) Write([]byte) (int, error) { return 0, errFull }

func TestCLI(t *testing.T) {
	t.Parallel()

	t.Run("main", func(t *testing.T) {
		t.Parallel()

		t.Run("writes the help to stdout and returns 0 for -h", func(t *testing.T) {
			t.Parallel()
			status, stdout, stderr := call("-h")
			assert.Equal(t, status, exitDetected, "the help is no error")
			assert.That(t, stdout).
				HasPrefix(name+" measures how well the tests of Go packages detect faults.\n", "the help starts")
			assert.Equal(t, stderr, "", "the help writes nothing to stderr")
		})

		t.Run("writes the error and a line on the help for a command line that is not valid", func(t *testing.T) {
			t.Parallel()
			status, stdout, stderr := call("-wokers", "2")
			assert.Equal(t, status, exitInvalid, "the command line is not valid")
			assert.Equal(t, stdout, "", "the command writes nothing to stdout")
			assert.Equal(t, stderr, name+": flag provided but not defined: -wokers\n"+usageLine,
				"the error is one line, and the pointer to the help another")
		})

		t.Run("writes the versions and returns 0 for -version", func(t *testing.T) {
			t.Parallel()
			status, stdout, _ := call("-" + flagVersion)
			assert.Equal(t, status, exitDetected, "the versions are no error")
			assert.ContainsInOrder(t, stdout, []string{name + " ", "\ncatalogue ", "\noverlay ", "\ntoolchain "},
				"the command states each version")
		})

		t.Run("returns 3 when standard output does not write", func(t *testing.T) {
			t.Parallel()
			var errs bytes.Buffer
			c := &cli{stdin: strings.NewReader(""), stdout: full{}, stderr: &errs, every: time.Hour, now: time.Now}
			status := c.main(t.Context(), []string{"-" + flagVersion})
			assert.Equal(t, status, exitFailed, "the command could not write the versions")
			assert.Equal(t, errs.String(), name+": standard output: "+errFull.Error()+"\n",
				"the error names the stream and its error")
		})
	})
}

// TestCLIProcess runs the test binary as the command, one process at a
// time.
func TestCLIProcess(t *testing.T) {
	t.Run("main", func(t *testing.T) {
		t.Run("exits with the status of the command line of the process", func(t *testing.T) {
			binary, err := os.Executable()
			assert.NoError(t, err, "the test binary's path reads")
			cmd := exec.Command(binary, "-"+flagParallel, "0")
			cmd.Env = append(os.Environ(), mainVar+"=1")
			var stderr bytes.Buffer
			cmd.Stderr = &stderr
			exit := assert.ErrorAs[*exec.ExitError](t, cmd.Run(), "the process fails")
			assert.Equal(t, exit.ExitCode(), exitInvalid, "the process exits with the command's status")
			assert.Equal(t, stderr.String(), "dokimi-mutate-go: -p takes a number of at least 1\n"+usageLine,
				"the process writes the command's error")
		})
	})
}

// TestCLIEnv changes the working directory and the environment of the test
// process, so neither it nor its subtests run in parallel.
func TestCLIEnv(t *testing.T) {
	t.Run("main", func(t *testing.T) {
		t.Run("prints the line of each undetected mutant when its verdict is final", func(t *testing.T) {
			enter(t, arithFiles)
			status, stdout, stderr := call()
			assert.Equal(t, status, exitUndetected, "mutants survive")
			assert.Equal(t, stdout, arithLines, "the lines follow the verdicts")
			assert.Equal(t, stderr, "", "the run writes nothing to stderr")
		})

		t.Run("returns 0 when the tests detect every mutant", func(t *testing.T) {
			enter(t, addFiles)
			status, stdout, stderr := call("-"+flagWorkers, "2")
			assert.Equal(t, status, exitDetected, "every mutant is killed")
			assert.Equal(t, stdout, addKilled, "the summary states the run")
			assert.Equal(t, stderr, "", "the run writes nothing to stderr")
		})

		t.Run("returns 3 when the record of a run does not write to standard output", func(t *testing.T) {
			enter(t, addFiles)
			var errs bytes.Buffer
			c := &cli{stdin: strings.NewReader(""), stdout: full{}, stderr: &errs, every: time.Hour, now: time.Now}
			status := c.main(t.Context(), []string{"-" + flagJSON})
			assert.Equal(t, status, exitFailed, "every mutant is killed, and the command could not write the record")
			assert.Equal(t, errs.String(), name+": standard output: "+errFull.Error()+"\n",
				"the error names the stream and its error")
		})

		t.Run("tests the packages in the directory of -C", func(t *testing.T) {
			dir := module(t, arithFiles)
			t.Chdir(t.TempDir())
			status, stdout, _ := call("-"+flagDir, dir)
			assert.Equal(t, status, exitUndetected, "mutants survive")
			assert.Equal(t, stdout, arithLines, "the paths are relative to the directory of -C")
		})

		t.Run("returns 2 for a directory of -C that does not exist", func(t *testing.T) {
			t.Chdir(t.TempDir())
			status, _, stderr := call("-"+flagDir, "missing")
			assert.Equal(t, status, exitInvalid, "the input is not valid")
			assert.HasPrefix(t, stderr, name+": -C: chdir missing: ", "the error names the directory")
		})

		t.Run("confirms each survivor in its ordinary build under -confirm", func(t *testing.T) {
			// TestSub checks Sub only in an ordinary build, so the
			// confirmation kills both of Sub's survivors.
			enter(t, arithFiles)
			t.Setenv(ordinaryVar, "1")
			status, stdout, stderr := call("-" + flagConfirm)
			assert.Equal(t, status, exitUndetected, "the mutants without coverage remain")
			assert.Equal(t, stdout, "arith.go:7:26: not covered: return x * 2 became return 0 (sbr-zero)\n"+
				"arith.go:7:33: not covered: x * 2 became x / 2 (aor)\n"+
				"fixture: 4 of 6 mutants detected (66%): 4 killed, 2 not covered\n", "the confirmations kill Sub's")
			assert.Equal(t, stderr, "", "the run writes nothing to stderr")
		})

		t.Run("tests the lines of -lines", func(t *testing.T) {
			enter(t, arithFiles)
			status, stdout, _ := call("-"+flagLines, "arith.go:5-5", "-"+flagLines, "arith.go:6-6")
			assert.Equal(t, status, exitUndetected, "Sub's mutants survive")
			assert.Equal(t, stdout, "arith.go:5:26: survived: return a - b became return 0 (sbr-zero)\n"+
				"arith.go:5:33: survived: a - b became a + b (aor)\n"+
				"fixture: 0 of 2 mutants detected (0%): 2 survived, 4 not selected\n", "the run tests Sub alone")
		})

		t.Run("resolves the paths of -lines in the directory of -C", func(t *testing.T) {
			dir := module(t, arithFiles)
			t.Chdir(t.TempDir())
			status, stdout, _ := call("-"+flagDir, dir, "-"+flagLines, "arith.go:5-6")
			assert.Equal(t, status, exitUndetected, "Sub's mutants survive")
			assert.Equal(t, stdout, "arith.go:5:26: survived: return a - b became return 0 (sbr-zero)\n"+
				"arith.go:5:33: survived: a - b became a + b (aor)\n"+
				"fixture: 0 of 2 mutants detected (0%): 2 survived, 4 not selected\n",
				"the entry names the file in the directory of -C")
		})

		t.Run("tests the lines that the diff of -diff changes", func(t *testing.T) {
			dir := enter(t, arithFiles)
			diff := "--- a/arith.go\n+++ b/arith.go\n@@ -5 +5 @@\n" +
				"-func Sub(a, b int) int { return b - a }\n+func Sub(a, b int) int { return a - b }\n"
			assert.NoError(
				t,
				os.WriteFile(filepath.Join(dir, "change.diff"), []byte(diff), fileMode),
				"the diff writes",
			)
			status, stdout, stderr := call("-"+flagDiff, "change.diff")
			assert.Equal(t, status, exitUndetected, "Sub's mutants survive")
			assert.Equal(t, stdout, "arith.go:5:26: survived: return a - b became return 0 (sbr-zero)\n"+
				"arith.go:5:33: survived: a - b became a + b (aor)\n"+
				"fixture: 0 of 2 mutants detected (0%): 2 survived, 4 not selected\n", "the run tests the changed line")
			assert.Equal(t, stderr, "", "the run writes nothing to stderr")
		})

		t.Run("tests no mutant for an empty diff on standard input", func(t *testing.T) {
			enter(t, arithFiles)
			status, stdout, stderr := call("-"+flagDiff, stdinPath)
			assert.Equal(t, status, exitDetected, "a run without a mutant passes")
			assert.Equal(t, stdout, "fixture: no mutant to detect: 6 not selected\n", "no line is selected")
			assert.Equal(t, stderr, "", "the run writes nothing to stderr")
		})

		t.Run("returns 2 for a diff that does not read or does not match the files", func(t *testing.T) {
			dir := enter(t, arithFiles)
			stale := "+++ b/arith.go\n@@ -5 +5 @@\n-func Sub(a, b int) int { return a - b }\n" +
				"+func Sub(a, b int) int { return b - a }\n"
			assert.NoError(
				t,
				os.WriteFile(filepath.Join(dir, "stale.diff"), []byte(stale), fileMode),
				"the diff writes",
			)
			arithPath, err := filepath.Abs(arithFile)
			assert.NoError(t, err, "the file's path resolves")
			tests := []struct{ give, want string }{
				{"missing.diff", name + ": -diff: open missing.diff: no such file or directory\n"},
				{"stale.diff", name + ": -diff: selection: the diff states line 5 of " + arithPath +
					" otherwise than the file, so it is out of date\n"},
			}
			for _, tt := range tests {
				status, stdout, stderr := call("-"+flagDiff, tt.give)
				assert.Equal(t, status, exitInvalid, "the diff is not valid")
				assert.Equal(t, stdout, "", "no package runs")
				assert.Equal(t, stderr, tt.want, "the error states the diff's problem")
			}
		})

		t.Run("counts the tests of the packages of -suite", func(t *testing.T) {
			dir := enter(t, with(arithFiles, map[string]string{
				"check/check.go": "package check\n",
				"check/check_test.go": "package check\n\nimport (\n\t\"testing\"\n\n\t\"fixture\"\n)\n\n" +
					"func TestSub(t *testing.T) {\n\tif fixture.Sub(5, 3) != 2 {\n\t\tt.Error(\"Sub(5, 3) != 2\")\n\t}\n}\n",
			}))
			// The working directory is a symbolic link to the module, and each
			// run resolves the suite in the package's directory, which go list
			// states without the link.
			link := filepath.Join(t.TempDir(), "link")
			assert.NoError(t, os.Symlink(dir, link), "the link is made")
			t.Chdir(link)
			status, stdout, _ := call("-"+flagSuite, "./check", "-"+flagSuite, "fixture/missing/...")
			assert.Equal(t, status, exitUndetected, "the mutants without coverage remain")
			assert.Equal(t, stdout, "arith.go:7:26: not covered: return x * 2 became return 0 (sbr-zero)\n"+
				"arith.go:7:33: not covered: x * 2 became x / 2 (aor)\n"+
				"fixture: 4 of 6 mutants detected (66%): 4 killed, 2 not covered\n", "the suite kills Sub's mutants")
		})

		t.Run("tests every package that the patterns name and writes their records", func(t *testing.T) {
			enter(t, twoPackages)
			records := t.TempDir()
			status, stdout, stderr := call("-"+flagParallel, "2", "-"+flagRecord, records, "./...")
			assert.Equal(t, status, exitDetected, "both packages pass")
			assert.Permutation(t, strings.Split(strings.TrimSpace(stdout), "\n"),
				[]string{"fixture/sub: 2 of 2 mutants detected (100%): 2 killed", strings.TrimSpace(addKilled)},
				"each package has its summary")
			assert.Equal(t, stderr, "", "the runs write nothing to stderr")
			for _, file := range []string{record.FileName(fixture), record.FileName(fixture + "/sub")} {
				_, err := os.Stat(filepath.Join(records, file))
				assert.NoError(t, err, "each package's record exists")
			}
		})

		t.Run("tests the packages within the memory of -memory-budget", func(t *testing.T) {
			// One byte admits the runs of one package at a time, and 0 sets no
			// budget. Both runs test both packages.
			for _, budget := range []string{"1", "0"} {
				enter(t, twoPackages)
				status, stdout, stderr := call("-"+flagParallel, "2", "-"+flagBudget, budget, "./...")
				assert.Equal(t, status, exitDetected, "both packages pass")
				assert.Length(t, strings.Split(strings.TrimSpace(stdout), "\n"), 2, "each package has its summary")
				assert.Equal(t, stderr, "", "the runs write nothing to stderr")
			}
		})

		t.Run("returns the status of the sample under -sample", func(t *testing.T) {
			enter(t, arithFiles)
			status, stdout, stderr := call("-"+flagSample, "2")
			assert.Equal(t, status, exitUndetected, "the sample's status is the status of its mutants")
			assert.Contains(t, stdout, "fixture: 2 of a sample of ", "the summary states the sample")
			assert.HasSuffix(
				t,
				stderr,
				name+": fixture: 2 mutants did not run: the caller limits the run to 2 mutants\n",
				"the note states the mutants beyond the sample",
			)
		})

		t.Run("divides GOMAXPROCS among the packages and then among the workers", func(t *testing.T) {
			enter(t, with(twoPackages, map[string]string{
				addTestFile: procsTest,
				"sub/add_test.go": strings.Replace(strings.Replace(procsTest, fixture, "sub", 1), expectedProcsVar,
					subProcsVar, 1),
			}))
			threads := runtime.GOMAXPROCS(0)
			// The first package starts beside the second, and the second gets
			// the threads that the first leaves free. Each package's workers
			// share its threads.
			first := max(1, threads/2)
			t.Setenv(expectedProcsVar, strconv.Itoa(max(1, first/2)))
			t.Setenv(subProcsVar, strconv.Itoa(max(1, max(1, threads-first)/2)))
			status, stdout, stderr := call("-"+flagParallel, "2", "-"+flagWorkers, "2", "./...")
			assert.Equal(t, status, exitDetected, "each run has the expected threads")
			assert.Length(t, strings.Split(strings.TrimSpace(stdout), "\n"), 2, "each package has its summary")
			assert.Equal(t, stderr, "", "the runs write nothing to stderr")
		})

		t.Run("writes each package's record as one line of JSON under -json", func(t *testing.T) {
			enter(t, addFiles)
			status, stdout, stderr := call("-" + flagJSON)
			assert.Equal(t, status, exitDetected, "the run passes")
			assert.Equal(t, strings.Count(stdout, "\n"), 1, "the record is one line")
			var rec record.Record
			assert.NoError(t, json.Unmarshal([]byte(stdout), &rec), "the line is a record")
			assert.Equal(t, rec.Target.Name, fixture, "the record states the package")
			assert.Equal(t, rec.Score, new(1.0), "and its score")
			assert.Equal(t, stderr, "", "the run writes nothing to stderr")
		})

		t.Run("lists the mutants of each package and runs no test under -list", func(t *testing.T) {
			enter(t, arithFiles)
			t.Setenv(failVar, "1")
			status, stdout, stderr := call("-" + flagList)
			assert.Equal(t, status, exitDetected, "a listing of a package whose tests fail passes")
			assert.Equal(t, stdout, "arith.go:3:26: to test: return a + b becomes return 0 (sbr-zero)\n"+
				"arith.go:3:33: to test: a + b becomes a - b (aor)\n"+
				"arith.go:5:26: to test: return a - b becomes return 0 (sbr-zero)\n"+
				"arith.go:5:33: to test: a - b becomes a + b (aor)\n"+
				"arith.go:7:26: to test: return x * 2 becomes return 0 (sbr-zero)\n"+
				"arith.go:7:33: to test: x * 2 becomes x / 2 (aor)\n"+
				"fixture: 6 mutants to test\n", "the listing states each mutant")
			assert.Equal(t, stderr, "", "the listing writes nothing to stderr")
		})

		t.Run("tests the mutants of the generated files under -include-generated", func(t *testing.T) {
			enter(t, map[string]string{"gen.go": generatedFile, "gen_test.go": generatedTest})
			status, stdout, _ := call("-" + flagIncludeGenerated)
			assert.Equal(t, status, exitDetected, "the test detects the generated file's mutants")
			assert.Equal(t, stdout,
				"fixture: 2 of 2 mutants detected (100%): 2 killed, 1 generated file with 2 mutants included\n",
				"the summary states the included file")
		})

		t.Run(
			"returns 3 for a run that fails, with the run error and the mutants that did not run",
			func(t *testing.T) {
				enter(t, arithFiles)
				t.Setenv(failVar, "1")
				status, stdout, stderr := call()
				assert.Equal(t, status, exitFailed, "the opening control run fails")
				assert.Equal(t, stdout, "fixture: the run failed: 6 not run\n", "the summary states the failure")
				assert.That(t, stderr).
					HasPrefix(name+": fixture: control-failed: the tests fail with no mutant active: TestAdd failed\n",
						"the note states the run error").
					HasSuffix("\n"+name+": fixture: 6 mutants did not run: the opening control run failed\n",
						"and the mutants that did not run")
			},
		)

		t.Run("starts no package after -timeout", func(t *testing.T) {
			enter(t, addFiles)
			status, stdout, stderr := call("-"+flagTimeout, "1ns")
			assert.Equal(t, status, exitFailed, "the package does not start")
			assert.Equal(t, stdout, "", "no package runs")
			assert.Equal(t, stderr, name+": fixture: not tested, because -timeout passed before the package started\n",
				"the note states why")
		})

		t.Run("starts no mutant that would not end before -timeout", func(t *testing.T) {
			enter(t, addFiles)
			status, stdout, stderr := call("-"+flagTimeout, "3s")
			assert.Equal(t, status, exitFailed, "the mutants do not start")
			assert.Equal(t, stdout, "fixture: the run failed: 2 not run\n", "the summary states the failure")
			assert.HasPrefix(t, stderr,
				name+": fixture: 2 mutants did not run: the caller's deadline leaves too little time for the ",
				"the note states why")
		})

		t.Run("starts no package after an interrupt", func(t *testing.T) {
			enter(t, twoPackages)
			ctx, cancel := context.WithCancel(t.Context())
			defer cancel()
			out := &cancelling{cancel: cancel}
			var errs bytes.Buffer
			c := &cli{stdin: strings.NewReader(""), stdout: out, stderr: &errs, every: time.Hour, now: time.Now}
			status := c.main(ctx, []string{"./..."})
			assert.Equal(t, status, exitFailed, "the interrupted package fails")
			assert.Equal(t, out.String(), addKilled, "the first package runs")
			assert.Equal(t, errs.String(), name+": fixture/sub: not tested, because the command was interrupted\n",
				"the note states why the second does not")
		})

		t.Run("writes the progress of each package that runs", func(t *testing.T) {
			// Each run of the test takes 200 ms, so a progress line every 10 ms
			// falls in the run of the second mutant.
			enter(t, map[string]string{
				addFile: add,
				addTestFile: "package fixture\n\nimport (\n\t\"testing\"\n\t\"time\"\n)\n\nfunc TestAdd(t *testing.T) {\n" +
					"\ttime.Sleep(200 * time.Millisecond)\n\tif Add(2, 3) != 5 {\n\t\tt.Error(\"Add(2, 3) != 5\")\n\t}\n}\n",
			})
			var out, errs bytes.Buffer
			c := &cli{
				stdin: strings.NewReader(""), stdout: &out, stderr: &errs, every: 10 * time.Millisecond,
				now: time.Now,
			}
			status := c.main(t.Context(), nil)
			assert.Equal(t, status, exitDetected, "the run passes")
			lines := strings.Split(strings.TrimSuffix(errs.String(), "\n"), "\n")
			progress := regexp.MustCompile(`^` + name + `: fixture: (running|[0-2] of 2 mutants done, 0 undetected, ` +
				`[0-9]+\.[0-9] mutants a second, about [0-9hms.]+ left)$`)
			assert.False(t, slices.ContainsFunc(lines, func(l string) bool { return !progress.MatchString(l) }),
				"stderr contains progress lines alone")
			assert.Equal(t, lines[0], name+": fixture: running", "the first line precedes the first verdict")
			assert.Contains(t, errs.String(), "\n"+name+": fixture: 1 of 2 mutants done, 0 undetected, ",
				"a later line states the mutants done")
		})

		tests := []struct {
			name   string
			setup  func(t *testing.T) []string
			status int
			want   string
		}{
			{"returns 2 for a pattern that names no package", func(t *testing.T) []string {
				t.Helper()
				enter(t, map[string]string{addFile: add})
				return []string{"./missing"}
			}, exitInvalid, name + ": ./missing: "},
			{"returns 2 for a pattern of -suite that names no package", func(t *testing.T) []string {
				t.Helper()
				enter(t, addFiles)
				return []string{"-" + flagSuite, "./missing"}
			}, exitInvalid, name + ": -suite: ./missing: "},
			{"returns 2 for a go list that fails", func(t *testing.T) []string {
				t.Helper()
				t.Setenv(pathVar, fakeGoDir+string(filepath.ListSeparator)+os.Getenv(pathVar))
				t.Setenv(fakeVar, fakeFail)
				return nil
			}, exitInvalid, name + ": go list -e -json=ImportPath,Dir,Error,DepsErrors .: exit status 1\nno list today"},
			{"returns 2 for a go list that prints no JSON", func(t *testing.T) []string {
				t.Helper()
				t.Setenv(pathVar, fakeGoDir+string(filepath.ListSeparator)+os.Getenv(pathVar))
				return nil
			}, exitInvalid, name + ": go list: invalid character"},
			{"returns 3 for a package that does not load", func(t *testing.T) []string {
				t.Helper()
				enter(t, map[string]string{addFile: add, "broken/b.go": "package broken\n\nfunc {\n"})
				return []string{"./broken"}
			}, exitFailed, name + ": fixture/broken: load: "},
			{"returns 3 for a run that cannot make its work directory", func(t *testing.T) []string {
				t.Helper()
				enter(t, addFiles)
				t.Setenv(tmpVar, filepath.Join(t.TempDir(), "missing"))
				return nil
			}, exitFailed, name + ": fixture: run: "},
			{"returns 3 for a record that cannot be written", func(t *testing.T) []string {
				t.Helper()
				dir := enter(t, addFiles)
				return []string{"-" + flagRecord, filepath.Join(dir, addFile)}
			}, exitFailed, name + ": record: "},
		}
		for _, tt := range tests {
			t.Run(tt.name, func(t *testing.T) {
				status, _, stderr := call(tt.setup(t)...)
				assert.Equal(t, status, tt.status, "the exit status states the class of the failure")
				assert.Contains(t, stderr, tt.want, "the error states the failure")
			})
		}
	})
}
